### ISSUE TITLE
Oh Noes gets stuck on the screen sometimes.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#201]
Make a programming error, then quickly remove the code. For some reason Oh Noes sticks.

**Comment by pamelafox** [comment]
@jeresig This may be related to what you're looking into? (Though this might be an older variant of it)

**Comment by kevinb7** [comment]
I believe that https://github.com/Khan/live-editor/commit/06e8d399710ada9a8d0f1fd69470e8a235db6803 fixes this.  I'm to close this.  Please re-open if you spot it again.
