### ISSUE TITLE
Support for keyframes declaration

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#204]
Slowparse doesn't support it yet, I filed this bug:
https://github.com/mozilla/thimble.webmaker.org/issues/452

We'll see if they respond, otherwise we can tackle it ourselves.

**Comment by kevinb7** [comment]
It's been fixed, see https://github.com/mozilla/slowparse/issues/62.  We just need to update our version.

**Comment by pamelafox** [comment]
Working on it (diff sent).

**Comment by pamelafox** [comment]
Fixed with slowparse upgrade
