### ISSUE TITLE
HTML: Internal links no longer work properly.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#219]
In Firefox (and I believe firefox only), internal site links on KA Programs no longer scroll as expected. 
How to reproduce:
Go here:
https://www.khanacademy.org/computing/computer-programming/html-css/html-tags-continued/p/html-internal-links
Go to the end of the video and attempt to click one of the links in the navigation. Nothing will happen.

Someone noticed this and posted on the video. I also noticed this recently and am posting this issue right now.

**Comment by pamelafox** [comment]
Thank you for the bug report, I've replicated and will look into it.

**Comment by pamelafox** [comment]
This is fixed.
