### ISSUE TITLE
HTML: External links are broken...

### ISSUE THREAD

**Issue by Gigabyte-Giant** [Khan/live-editor#227]
...in Safari 8.0.2, external links do not work at all.

When you click on an external link, you do receive a prompt letting you know the link was on a user-created page, and all that good stuff. Whenever you click "ok", nothing happens. No redirect, it doesn't even open a new tab.

Steps to reproduce:
1). Go to the end of https://www.khanacademy.org/computing/computer-programming/html-css/html-tags-continued/p/html-links
2). Click on any of the links
3). Click "ok", when prompted.
Nothing happens...

On the other hand, internal links are working great now!

Added a screencast: http://gigabytegiant.com/blog/wp-content/uploads/2015/01/Reproducing-Error.mov

**Comment by MikaalSky** [comment]
Everything's right in the world of Firefox and Chrome so I can confirm that this is just a bug that occurs on Safari.
Anyway, any errors in the javascript console when you hit Ok?

**Comment by Gigabyte-Giant** [comment]
No errors are produced when clicking "ok".

**Comment by pamelafox** [comment]
Thanks for the report, we'll look into this.

**Comment by Gigabyte-Giant** [comment]
@pamelafox After a bit of investigation, I have determined that this is in-fact due to Safari's default setting to block pop-ups.

As for what you could do to prevent this, I'm still unsure.

If you open Safari 8.0.2, go to Safari > Preferences > Security, and then un-check block pop-up windows.
Now revisit the end of https://www.khanacademy.org/computing/computer-programming/html-css/html-tags-continued/p/html-links
Click on any of the links.
Click "ok", when prompted, and you'll be redirected to the site you requested.

That's a bit more work than some people would like to do, just to be able to click on links in user-created webpages.

The problem can be avoided by Mac users of KA by either disabling their popup blocker (not ideal), or downloading a new browser (also not ideal for some users)...

**Comment by pamelafox** [comment]
I changed how links work, they now go through a redirect proxy, so popup blockers should no longer be an issue.

**Comment by Gigabyte-Giant** [comment]
Awesome, thanks Pamela, I appreciate it.
