### ISSUE TITLE
Programs that have a title that is just symbols don't save correctly.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#229]
If you save a program under, lets say, the apple logo symbol on an apple computer, if you attempt to open the program by clicking on it you'll get a link like
https://www.khanacademy.org/computer-programming//numbers
when in all reality you should get a link like
https://www.khanacademy.org/computer-programming/program/numbers

**Comment by pamelafox** [comment]
Thanks for report, the fix for this will go out today or tomorrow.

**Comment by pamelafox** [comment]
Fix is live.
