### ISSUE TITLE
PVector.dist() doesn't work with set()ed PVector()s

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#230]
Report from Bob Lyon:
"After using the .set method of a PVector, using it as an argument to PVector.dist does not work.

Go to your page at
https://www.khanacademy.org/computer-programming/pvectorsetx-y/6355569514381312
and try it.  Simply add this to the end:

var d = PVector.dist(v1, v2);
println(d);

You will find that d is NaN."

**Comment by kevinb7** [comment]
The problem is that ```v1.set(20.0, 30.0);``` from the example doesn't provide a ```z``` parameter and so ```z``` is set to be ```undefined```.  I'm going to fix this by setting ```z``` to ```0``` if it's ```undefined```.

**Comment by kevinb7** [comment]
I didn't realized commit messages could automatically close issues.
