### ISSUE TITLE
[Bug] A { in string autocompletes

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#232]
Type var x = "{", see it autocomplete.

I'm personally a fan of disabling that particular autocomplete, as long as we update ScratchpadConfig accordingly and don't break talk-throughs (if that's even needed now with the new recording system?).
I dislike it because of how much work it is to undo, and how easily it is to type { when you're trying to type P. And also because there are various situations where you don't want } on a new line.

**Comment by MikaalSky** [comment]
Yeah. I'm not a fan of that either. Maybe some detection of it being inside of a string or just some work on that auto-completion would be nice.

**Comment by pamelafox** [comment]
We have now removed the object autocomplete behavior entirely.

**Comment by MikaalSky** [comment]
Re-enabling it for just draw and other built-in functions would be nice, though

**Comment by SpongeJr** [comment]
It still autocompletes on HTML projects inside the <script> tag, at least in some situations. (Not in JS projects, nor outside the script tag of HTML projects, from what I can tell).

Test case:
Type (don't copy/paste):
var foo = {
into a blank (template) HTML project inside a <script> tag. Hit enter after open curly-brace and a closed curly-brace will appear on a new line, after the blank line.

Personally, the behavior doesn't bug me either way, or even the inconsistency... just pointing it out.
