### ISSUE TITLE
Reports of issues with loops in IE 11

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#249]
We've had several reports of issues with loops in IE 11.

For example, on "a loopy landscape".

Also on
https://www.khanacademy.org/computing/computer-science/algorithms/binary-search/p/challenge-binary-
if you type
while (true) { }

I have replicated a few times but not 100% of the time.

**Comment by kevinb7** [comment]
The link should be: https://www.khanacademy.org/computing/computer-science/algorithms/binary-search/p/challenge-binary-search.

Does the browser freeze?

**Comment by pamelafox** [comment]
That's what the reports say, but in my most recent attempt, I can't replicate it. Closing for now.
