### ISSUE TITLE
getSound doesn't function in Live Editor Demo

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#255]
http://prntscr.com/65ypej
It just refuses to work.

Also, I'll just make this a point, when you run the live editor on your own webserver with the latest revision, it acts differently.

**Comment by kevinb7** [comment]
That's really weird that ```getSound``` is undefined.  When I run ```demos/index.html``` locally I load it using a local web server.  I don't the "Oh noes!" you're seeing.  @MikaalSky can you send me a link to your web server, maybe I can diagnose what's going on?

**Comment by MikaalSky** [comment]
I'll put it up in a bit.

**Comment by kevinb7** [comment]
Closing.  Please reopen if this is still occurring.
