### ISSUE TITLE
Webpages not updating immediately after changing the color

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#256]
Open https://www.khanacademy.org/computer-programming/results-for-contest-fabric-pattern/6250308077092864 in Chrome, try changing rgb(), color does not update immediately.

Seems like a regression bug, possibly due to recent number scrubber change from @kevinb7. Haven't looked into it yet.

**Comment by MikaalSky** [comment]
The page is updating, though. Notice the flashing of link colors.

**Comment by MikaalSky** [comment]
Alright, this is happening in Firefox, also. An error is getting fired.
TypeError: list is undefined
If you can't replicate, move the color selector circle around very fast.

**Comment by kevinb7** [comment]
I will look into this.
