### ISSUE TITLE
Infinite loop detection in webpages pops up after tab switch

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#260]
This code can result in an infinite loop error:
```
  <!DOCTYPE html>
  <html>
  <head>
      <meta charset="utf-8">
      <title>Animation starter</title>
  </head>
  <body>
  <div>
  <img src="https://www.kasandbox.org/programming-images/creatures/OhNoes.png">
  <h1>Oh noes, the world will end in
      <span id="countdown">500</span>
      seconds!
  </h1>
  
  </div>
  
<script>
// Step 1. What element do we want to animate?
var countdown = document.getElementById("countdown");
// Step 2. What function will change it each time?
var countItDown = function() {
  countdown.innerHTML = countdown.innerHTML - 1;  
};
// Step 3: Call that on an interval
window.setInterval(countItDown, 1000);
</script>

  </body>
  </html>
```

Investigation from john:
It only happens if you tab away from the page with the code and leave it in the background. After some amount of time (haven't pinned it down yet) this code doesn't fire at the right time:

setTimeout(function() {
    this.branchStartTime = 0;
}.bind(this), 0);
since the page is in the background the timers aren't run in the right order. The hiccup looks something like this:
https://www.dropbox.com/s/ulq0um8r7m4f3ws/Screenshot%202015-01-28%2013.58.40.png?dl=0

One thought is to use the page visibility API to not do checking while the page is in the background:
https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API

**Comment by kevinb7** [comment]
I had a look at the loop protector code.  Using page visibility to disable/enable the loop protector seems like it would work and wouldn't be too much effort.  I wonder if something similar to this would help with infinite loops in pjs environment.

**Comment by kevinb7** [comment]
Page Visibility API isn't supported in IE9, but I found an polyfill that I'm going to try out: https://gist.github.com/addyosmani/1122546.

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/live-editor/commit/6b3b5e505179649c1a291d1dcfe76872b463ee0a.
