### ISSUE TITLE
Autocomplete of color() inside array produces unnecessary semi-colon

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#262]
For example:
```
var bla = [
  color: color(255, 0, 0);
];
```
We could decide to never put the semi-colon for that autocomplete. Or be smarter via regex/ast. 
Or decide that students can figure it out, which I'm sure they do. :-)

**Comment by pamelafox** [comment]
This is a more important issue now as it's affecting a challenge that will come out soon. I'll raise priority internally as well.

**Comment by kevinbarabash** [comment]
It's probably best to just leave the semi-colon out.  I can't think of a good way to regex/ast this problem.  Having to always add the semi-colon gets them into the habit of doing so.

**Comment by pamelafox** [comment]
Just for color(), do you mean? The semi-colon is handy for fill/stroke, because you can immediately start picking your color and see the effect, and you don't have to fix a syntax error first.

Leaving it out for color() seems reasonable to me. Hopefully I haven't used it in any talk-throughs, as it could potentially affect them if I did. (Though we technically have versioning which helps).

**Comment by kevinbarabash** [comment]
Hmm... good point about seeing the effect immediately.  Maybe we only do it for `color` and `getImage` and functions that return values.  We could look at what comes before the call to `color`.  We're already checking if we're inside of a function call, e.g. `foo(color(255, 0, 0)` inserts color without the `;`.  We could check if there's a `:` in front of us.

**Comment by petercollingridge** [comment]
I would vote for leaving off the semi-colon altogether - it's also a problem when you make an array of colors (as I often do). The same is true with and array of images using `getImage`.

**Comment by jeresig** [comment]
@pamelafox @kevinbarabash @petercollingridge I have two possible fixes for this but I'd like your feedback:

**Option 1:** We already do detection to determine if we're currently inside a "parenthesis" (this includes `[ ( {`) and then don't insert a `;` if we are. However we only look on text on the same line to make this determination. Thus right now if you type `foo(color(` or `foo(getImage(` it will auto-complete without a semicolon. However if you do:

```
var a = [
    getImage(
```

Then it'll auto-complete with a semicolon. If we pull in the entire document we could parse it and see if we're currently inside a parenthesis. The problem with this solution is that it would require reading in (and parsing) the entire document on every key press, which would almost certainly cause problems, even though it would be accurate.

**Option 2:** We change the code to never insert a semicolon, except when the function is prefixed with a `=`. Thus this would catch cases like `var a = color(` and `var a = getImage(`. Technically this would be simple to implement and would have little overhead, although it's possibly a more brittle solution.

Thoughts?

**Comment by MikaalSky** [comment]
Why don't we use the AST and check if it's inside of a node (I think thats what it's called) and if it is, don't put a semicolon.

**Comment by jeresig** [comment]
@MikaalSky The tooltip logic doesn't appear to have access to any of the AST code, as far as I can tell.

**Comment by pamelafox** [comment]
Option 2 seems okay to me. What brittleness would you foresee there?

**Comment by jeresig** [comment]
@pamelafox Hard to say! Maybe cases like `if (foo === color(` causing problems? Although in thinking about it that would also not insert a `;` as that'd be inside a semicolon. But yeah, maybe that solution is just better than a perfectly-ideal solution.

**Comment by Gigabyte-Giant** [comment]
I don't think expressions would be a problem @jeresig, couldn't you just use a strict(er) regular expression to make sure that there's only a single `=`?

**Comment by GoToLoop** [comment]
JS' internal parser doesn't demand semicolons. So enforcing them got little (if any) actual benefit!
https://www.YouTube.com/watch?v=Qlr-FGbhKaI

**Comment by petercollingridge** [comment]
Option 2 sounds reasonable to me. I think that would work for all the situations I've encountered.
