### ISSUE TITLE
BabyHint's checkFunctionParams incorrectly identifies errors in "for" and "while" loops as a function call error

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#264]
Given this code:
```
/* Visualize the distribution of numbers generated by 
 * the random function in ProcessingJS
 */

// Set initial variables and colors
var randomCounts = [];
for (var x = 0; x < 20; i++) {
    randomCounts[x] = 0;
}
var rectWidth = floor(width/randomCounts.length);
stroke(0, 0, 0);
fill(173, 173, 173);

// Animate the distribution of random numbers over time
var draw = function() {
  background(255, 255, 255);
 
  var index = floor(random(randomCounts.length));
  randomCounts[index]++;
  
  for (var x = 0; x < randomCounts.length; x++) {
    rect(x*rectWidth,
        height-randomCounts[x],
        rectWidth-1,
        randomCounts[x]);
  }
};
```

The first outputted error is about commas, the second error (and the actual one) is about i being undefined. That's the one that we should show.

**Comment by shenningsgard** [comment]
Is it possible this is related to the following JSHint issue:

""nocomma" shouldn't apply to array/object literals and parameter lists"
https://github.com/jshint/jshint/issues/2044

**Comment by kevinb7** [comment]
@shannonzhu is this fixed?

**Comment by shannonzhu** [comment]
It isn't! I can probably work on it on Monday before my next project kicks off - I'm sorry for not being on top of this in the meantime. Let me know if you'd want to reassign it or if I should re-prioritize and look at this asap :)

**Comment by kevinb7** [comment]
I should've looked at the LintLove doc first.  I didn't realize this was a "bonus".  If you have time, cool, if not just un-assign yourself.

**Comment by shannonzhu** [comment]
Skill checks spilled over a bit and turns out I don't think I have time to look at this between projects - I'm doing support in a couple weeks and could work on it then, or if someone else wants to take a stab that'd be awesome! Sorry about leaving this untouched for so long :/

**Comment by kevinb7** [comment]
I tried the code on jshint.com and it doesn't say anything about a missing comma.  We're at jshint 2.4.0 right now, but the most recent version is at 2.8.0.  We should upgrade and use a package manager for this dependency.

**Comment by kevinb7** [comment]
I started investigating and it's not jshint.  It's actually BabyHint that's generating this error.  I'll investigate further and hopefully will come up with a fix.

**Comment by kevinb7** [comment]
It should not recognize errors in `for ( ... )` or `while ( ... )`.

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/live-editor/commit/b0832d690dd36d8c720da3d46672b9aa94aeb5ff.

**Comment by ITkorea** [comment]
var randomCounts = [];
for (var x = 0; x < 20; i++) {   // you have a problem here!!!   not i ++  but x++     
    randomCounts[x] = 0;

**Comment by kevinbarabash** [comment]
@ITkorea once we've determined that "i" is undefined we could determine if there are other variables that are defined that the user might have meant and suggest those.
