### ISSUE TITLE
Add a warning about missing semi-colons at the end of their CSS values

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#268]
This is a little tricky to detect, but chrome at least detects that the value becomes malformed due to it.

Example problematic CSS that we issue no warnings at all about:
```
.photo {
                border:2px,double,red;                      
                margin-left:5px
                width: 200px;
            }
```

One one hand it is a valuable debugging experience to find that missing semi-colon, but most people just don't see it, from my experience.

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/live-editor/pull/412.
