### ISSUE TITLE
Possibly warn users if they remove the DOCTYPE or HTML tag

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#271]
Some students are curious why they can remove DOCTYPE and HTML and nothing bad happened. We could potentially warn about that in slowparse or a different validation step (if we did more w3 validation style errors).

**Comment by MikaalSky** [comment]
If you did that it should appear on a list of warnings, not Error Buddy. Mostly due to it just not being an error.

**Comment by MikaalSky** [comment]
With the new upcoming error buddy design, this might work nicely.
