### ISSUE TITLE
Explore using ESlint instead of JSHint

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#272]
It might be 1) faster and 2) give us more flexibility.

However, we'd need to make sure we didn't break older programs (like use our config versioning system for it) and that ESlint could support everything we're doing now.

This would be a large task to take on.

**Comment by kevinb7** [comment]
I looked into this a little bit before and decided against mainly because it's supposedly 2-3x slower than JSHint.  Here's some more detail from the horse's mouth: https://github.com/eslint/eslint#how-does-eslint-performance-compare-to-jshint
