### ISSUE TITLE
Extra "," in objects or arrays should throw errors

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#277]
If a user types
`var object = {
 "a" : 3,
}`
Or
`var array =[2,];`
No error is thrown. Errors should be thrown for the object but the array isn't as important.

**Comment by Gigabyte-Giant** [comment]
...might I ask why you think an error should be thrown?
For an array, it might not be a great idea to throw an error, as sometime it's useful to use blank indices, for create a level map, among other things.
Example:
```var myMap = [
    [ , , , , ],
    [ , , , , ],
    [ , , , , ],
    [ , , , , ],
    [ , , , , ]
];```

**Comment by MikaalSky** [comment]
Arrays are less of a concern. Objects, though, would be an okay thing to throw an error for.

**Comment by Gigabyte-Giant** [comment]
That brings me back to my original question.
In your opinion, why should an error be thrown?

**Comment by kevinb7** [comment]
A trailing comma is not strictly an error in ES5 and IE8+ can handle this.  khanacademy.org supports IE9+ so I don't think this is an issue.
