### ISSUE TITLE
Thrown error "string is not a function" on Asteroids blaster

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#279]
1. Visit https://www.khanacademy.org/computer-programming/challenge-asteroid-blaster/6589920608518144
2. Make a code change.
3. Check console, see error.
4. Reload, it works.

Likely an error with our dynamic draw injection code.

**Comment by MikaalSky** [comment]
This happens on pretty much every oop program. If you edit constructor code it freaks out but if you edit any of the other referenced functions it deals with it. Also it seems to only happen if you're editing a function that's in use.

**Comment by embalingit** [comment]
There's an often encountered bug that occurs as draw() begins to cycle, seemingly before (or without) any binding to the processing instance (or to the whole of the environment scope) - honestly I'm not sure of the details.  If you can track that down it may be the source of many errors.

I deal with it by including the following code (or an if/try/catch) inside the draw method:

var draw = function(){
    if(!this.loadPixels){
        return;
    }
    
    // let her rip!

};

When running complex code you typically get at least one draw that fails before everything is in order.

**Comment by kevinb7** [comment]
Fixed in https://github.com/Khan/live-editor/commit/06e8d399710ada9a8d0f1fd69470e8a235db6803.
