### ISSUE TITLE
Maybe try using P5.js?

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#286]
P5.js is built by the people behind processing and I think it could be an improvement. Just a suggestion, though.

**Comment by Gigabyte-Giant** [comment]
I'm pretty sure the live-editor repo isn't the place to make a suggestion, perhaps try the Computer Science forum on zendesk.

https://khanacademy.zendesk.com/hc/communities/public/topics/200153574-Computer-Science

**Comment by pamelafox** [comment]
I'm fine with raising ideas here that would be implemented in this repo, but as a heads up, the primary changes we'll be making in the near future (3 months) will be small bug fixes. We don't currently have the engineering resources to make any other changes, or even spend a lot of time discussing them.  I'll make an "idea" label for issues like this.

By the way, we have considered P5.js and decided not to pursue it for now, as there doesn't seem  to be a big enough benefit. We think it'd be better/safer to remove unused code from our ProcessingJS variant, and bring in other performance improvements from P5.

**Comment by MikaalSky** [comment]
Yeah. Well it would be cool to see something like this.

**Comment by MikaalSky** [comment]
I might try to implement P5.js into the editor in a pull request and just make baby hint not touch it.

**Comment by jeresig** [comment]
@MikaalSky it isn't an implementation problem though. There are direct incompatibilities between P5.js and Processing.js. If we were to switch to P5.js it would break a large number of user programs, which is something that we wish to avoid, if at all possible.

**Comment by MikaalSky** [comment]
I'm just saying that I would personally like to make an addition using P5, seperate from the PJS.

**Comment by kevinb7** [comment]
I was in the process of porting processing.js test over to P5.js and there were many things that the tests picked up and I haven't finished porting all of them.

@MikaalSky what benefits do you see using P5.js over processing.js?

**Comment by MikaalSky** [comment]
I just really wanna use P5 since it's mostly like Processing and I'm making a game in processing with a team I'm in.

**Comment by Gigabyte-Giant** [comment]
@MikaalSky Said:
> I'm just saying that I would personally like to make an addition using P5, seperate from the PJS.

So you're proposing that they invest time on create **another** "branch" of the live-editor, for P5? I really don't see how that would be worth the time.
When asked for the benefits of P5 over Processing(.js), you said:
> I just really wanna use P5 since it's mostly like Processing and I'm making a game in processing with a team I'm in.

Which means, you don't really see any (*major*) benefits, aside from the fact that *you* want it. Sure, there are some very neat things in P5, but a majority of the stuff in it, would have to be modified (or even disabled) by the CS team. It's great that P5 looks and feels like Processing, but, is that really something that the CS community is worried-about/focused-on, right now?

Sorry for the quite long post, just wanted to throw some stuff out there.
@MikaalSky if you can come up with a list of benefits for P5 over PJS, I'd love to see them!

**Comment by kevinb7** [comment]
I was investigating how much work it would be to integrate P5 on a branch, see: https://github.com/kevinb7/live-editor/tree/page_speed.

The main benefits I saw were:
- modularity
- smaller codebase
- plugins (dom, sound)

One of the biggest drawbacks of P5 is that it isn't a re-implementation of processing.js, but a re-interpretation, meaning that some of the APIs are different or they behave differently.  Because of this, it's probably more feasible to modify processing.js to be more modular and support plugins than to try to make P5.js be 100% compatible with processing.js.

**Comment by MikaalSky** [comment]
Well, if it ever got combined that would be cool, but you could probably just teach P5 as processing and not baby it (except removal of externals and such) as much as PJS was.

**Comment by pamelafox** [comment]
I'm going to close this issue, as Kevin gave a great list of reasons for why we're not going to implement P5 anytime soon. As he said, we'd rather get the same improvements on Processing, and not have to introduce backwards compatibility issues to do that.
You can probably use P5 in the new /webpage environment if you'd like its functionality.

**Comment by MikaalSky** [comment]
Oh, forgot about that. Thanks @pamelafox
