### ISSUE TITLE
Example Program on the Demo throws error.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#287]
playSound is still not recognised by the demo.
http://khan.github.io/live-editor/demos/simple/

**Comment by kevinb7** [comment]
The last time gh-pages was updated was Dec. 5, 2014 so it's out of date by quite a bit.

**Comment by kevinb7** [comment]
@pamelafox I'd like to make gh-pages a submodule of master so that it's easy to update the demo.

**Comment by kevinb7** [comment]
This is fixed.
