### ISSUE TITLE
Picky challenge

### ISSUE THREAD

**Issue by OldKingCode** [Khan/live-editor#288]
The challenge "Shining Scaling Sun" does not easily accept correct code. Maybe add more flexibility to the check.

**Comment by MikaalSky** [comment]
Not impossible then, suggesting a rename to "Picky Challenge"

**Comment by OldKingCode** [comment]
Done

**Comment by kevinb7** [comment]
@OldKingCode can you post some examples that it should be accepting but isn't?

It's possible that this issue by solved by https://github.com/Khan/structuredjs/pull/10.

**Comment by pamelafox** [comment]
Please use "Report a problem" on the challenge to send through examples of code that should pass. It'll send all of the relevant information to me. It is indeed a picky challenge.
