### ISSUE TITLE
Firefox refuses to load programs.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#292]
http://prntscr.com/6nh10e

**Comment by Gigabyte-Giant** [comment]
Same problem in Chrome and Safari. Cannot get an error message in IE, but programs won't load, at all.

**Comment by Gigabyte-Giant** [comment]
Appears to be fixed as of 5:34PM CST.

**Comment by MikaalSky** [comment]
yeah, please report downtime stuff like this.
