### ISSUE TITLE
Error in real-time evaluation in complex OO code

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#300]
1. Open https://www.khanacademy.org/computer-programming/karel-newspaper/6643911212400640
2. Un-comment move on line 734.
3. See error "debug is not defined"
4. Click restart and notice it goes away.

Most likely same or similar bug as https://github.com/Khan/live-editor/issues/279

Also very likely the issue is in injectCode:
https://github.com/Khan/live-editor/blob/master/js/output/pjs/pjs-output.js#L843

**Comment by pamelafox** [comment]
Related:
1. Go to: https://www.khanacademy.org/computing/computer-programming/programming-games-visualizations/side-scroller/p/project-hoppy-beaver-extreme
2. Paste in:
`
var rottenStick = function(x, y) { 
this.x = x; 
this.y = y; 
}; 
`
3. See 'fill is not defined'. It goes away upon restart.

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/live-editor/commit/44bbaa208b61cbd71f50610b775fd49a9229b410.
