### ISSUE TITLE
Failing to load large programs

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#301]
https://www.khanacademy.org/computer-programming/front-line-v6872-gamma/5994354862456832
Most of the time, the program will fail to load due to the corelibs script hanging.

According to Firefox, corelibs hangs on line 1310.

**Comment by MikaalSky** [comment]
Seems like it has to do with 1.2k lines of code.

**Comment by MikaalSky** [comment]
Actually, it does not. Strange.

**Comment by pamelafox** [comment]
I reverted the structuredJS change that introduced the performance regression, so this is now fixed.

**Comment by DozenalFTW** [comment]
Is this still a problem?

**Comment by kevinbarabash** [comment]
I don't believe so unless you're seeing an issue.
