### ISSUE TITLE
You can't scroll the output window when a SQL error pops up

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#303]
Someone wanted to scroll up to look at their schema/results to fix up their query, but they couldn't do that with the semi-opaque error-overlay on top:
![screen shot 2015-04-27 at 4 46 52 pm](https://cloud.githubusercontent.com/assets/297042/7360234/08445aec-ecfd-11e4-9082-70a3fcc62218.png)

If we removed the error-overlay and made EB opaque, this is what it'd look like:
![screen shot 2015-04-27 at 4 44 28 pm](https://cloud.githubusercontent.com/assets/297042/7360241/143ba49a-ecfd-11e4-8c00-cdc4746e6514.png)

I think that'd be a better experience for SQL users, since they can scroll behind, but it does have the effect of not making it quite as obvious that the program is an error state. (Still pretty darn obvious though, I think!).

Thoughts @bbondy ? I can make the change if it sounds good.

**Comment by kevinb7** [comment]
You should be able to set ```pointer-events: none``` on the overlay.  Then set ```pointer-event:all;``` on the message ```<div>``` otherwise users won't be able to click "Show me where".

**Comment by bbondy** [comment]
What Kevin said sounds best, I'm fine with getting rid of the overlay if that doesn't work for some reason.
