### ISSUE TITLE
Some programmers want to be able to disable auto-suggest

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#311]
This could possibly be implemented in this repo, if it was disabled via some settings menu in the editor itself and the setting remembered in local storage. It might be better to implement it in the internal KA code, so that it could be stored more persistently and surfaced somewhere else.

**Comment by Gigabyte-Giant** [comment]
Instead of a menu, how about a keystroke? I know a keystroke might be more difficult for newer, less experienced users, but, the way I look at it; how many beginners will be wanting to disable the auto-suggest?

RE "could possibly be implemented in this repo":
I might make a fork and take a crack at it! :)

**Comment by pamelafox** [comment]
I think if we could bring an advanced menu up via a series of keystrokes (ctrl+alt+m or some not taken combination), then you could turn off the autocomplete there, and save that setting to localstorage. The Ace editor may already have a settings menu capability, that is the first thing I'd investigate.
Would love a pull request on this!

**Comment by Gigabyte-Giant** [comment]
It has a settings menu, yes.

`Cmd + ,` on Mac, and `Ctrl + ,` on PC. Will look into this and try to submit a PR soon (hopefully today, but no promises)!

**Comment by kevinb7** [comment]
@Gigabyte-Giant looking forward the pull request.

**Comment by Gigabyte-Giant** [comment]
PR will hopefully come later tonight. I think I have everything working properly, I've just gotten stuck on trying to build everything...

I do apologize about the wait.

**Comment by kevinb7** [comment]
Is building still not working for you?  If so, can you post some details, maybe I can help.

**Comment by Gigabyte-Giant** [comment]
Yup, build gets going good, and then it just stops. Occasionally I see the following:
```TypeError: 'undefined' is not a function (evaluating 'this.merge(helpers, Handlebars.helpers)')```

I did see the message in this repo that says "If you have an issue with "this.merge" is undefined, then rm-rf the handlebars that's inside node_modules/gulp", however, said file/directory doesn't exist as it would appear...

**Comment by kevinb7** [comment]
I know that we have issues with conflicting versions of handlebars which I've had to deal with in the past.  You might try this suggestion from bbondy:
> I ran into that handlebars issue recently too and @lemiant suggested a work around that worked for me, just rename:
live-editor/node_modules/gulp-handlebars/node_modules/handlebars to live-editor/node_modules/gulp-handlebars/node_modules/_handlebars

I think maybe that's the handlebars that the README is referring to.

**Comment by Gigabyte-Giant** [comment]
Will see if that works! Thanks for the response!

**Comment by Gigabyte-Giant** [comment]
That appears to have worked for that one problem @kevinb7, but now the build just gets hung after finishing the stuff for the images... No errors so far however!

**Comment by pamelafox** [comment]
Hm, when you say hung, that might be on purpose? Gulp is set to "watch" and
re-build when files are updated, so maybe it's watching right now?

**Comment by Gigabyte-Giant** [comment]
Not exactly sure @pamelafox, it stops printing any messages to the console after it finishes with images...

**Comment by Gigabyte-Giant** [comment]
Actually, that **is** what it's doing. Just added a comment to the live-editor.js file to see if that was the case, and sure enough it was. Thanks for pointing me in the right direction @pamelafox!

**Comment by kevinb7** [comment]
https://github.com/Khan/live-editor/pull/323 has been deployed to khanacademy.org.  Users can now try it out by adding ```autosuggestToggle=yes``` to the query string and cmd + opt + a on Mac and ctrl + opt + a on PC to toggle autosuggest.

I'm going to leave this issue open b/c I think @Gigabyte-Giant you were going to add a settings menu to toggle settings like this.

**Comment by Gigabyte-Giant** [comment]
@kevinb7 I am working on adding a settings menu/command palette for things like this, yes.

**Comment by kevinb7** [comment]
Awesome!  Can't wait.  ^_^

**Comment by Gigabyte-Giant** [comment]
This should probably be closed, shouldn't it, since [auto-suggest was disabled](https://github.com/Khan/live-editor/commit/4e028ca5d15d3b062a4a9b38fd4033ddb1a75758)?

**Comment by kevinbarabash** [comment]
@Gigabyte-Giant yup, that makes sense.
