### ISSUE TITLE
createGraphics properties are not working as expected

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#312]
Reported in ZenDesk:
https://khanacademy.zendesk.com/agent/tickets/91990/events

Shown in this program:
https://www.khanacademy.org/computer-programming/transparent-images/5683689601892352

JPG2000 says that it appears to be a regression, but not sure from what date/change.
It likely has to do with injectCode or related functionality.

**Comment by kevinb7** [comment]
Fixed in https://github.com/Khan/live-editor/commit/b7b371de00dc0c677c056fd7358cbe8639f2e710.
