### ISSUE TITLE
migrate to ES6 so that we can use fat arrow

### ISSUE THREAD

**Issue by kevinb7** [Khan/live-editor#329]
We do a lot of ```function (...) { ... }.bind()```, it would be nice if we could do ```(...) => { ... }``` instead.

**Comment by MikaalSky** [comment]
Make sure to take something like this into consideration:
https://kangax.github.io/compat-table/es6/

**Comment by kevinb7** [comment]
We'd use http://babeljs.io/ to compile down to ES5.

**Comment by kevinb7** [comment]
Implemented in https://github.com/Khan/live-editor/commit/1a2375ddb8cd0c190b7cbea5e9cb3a6e0e40e5ad.
