### ISSUE TITLE
AceEditor Edit to Fix some CR+LF Issues

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#333]
Brought to my attention by @SpongeJr ...
CR + LF causes double-spacing on windows computers when copy-pasting ka code in another program and saving. If we could axe off the LF or the CR and leave it with only one, that would be helpful. Otherwise you get code that looks like

var a = "Hello!";

draw = function() {

**Comment by pamelafox** [comment]
Do you also see this issue on http://ace.c9.io/ on Windows ?

**Comment by MikaalSky** [comment]
The issue surfaces when you save the program and it's encoded into the \n statements. Once that happens, you get double new lines.

**Comment by SpongeJr** [comment]
We've been seeing a couple recent support tickets pertaining to this as well. We also see Help Requests about it now and then, and it's a general frustration with quite a few learners.

MikaalSky's description explains the reason behind it I believe.

**Comment by Gigabyte-Giant** [comment]
So, after a quick glance, I'm thinking that the regex on [this line](https://github.com/Khan/live-editor/blob/3421853a2544ea9cc8372f9b015a68c645570201/js/editors/ace/editor-ace.js#L421), should probably be changed to `/\r\n/g`...

Problem is, I'm having a hard time reproducing this issue... I'll continue to dig around.
