### ISSUE TITLE
HTML5 Canvases getting Taking too long!'d

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#334]
This program here:
https://www.khanacademy.org/computer-programming/html5-drawing-program/4856337809932288
Utilizes an HTML5 Canvas to render a nice whiteboard that you can draw on. If you tab out, though, KA's infinite loop protection kicks in and kills the webpage. I'm not sure how this could be fixed, tbh, but I'm sure someone will come up with something.

**Comment by kevinb7** [comment]
Good find.  I found that you have to be on another tab for a while before the issue manifests.  It also occurs if you switch to another application.  I'm guess we have some code some where that uses the Page Visibility API and it's doing the wrong thing with regards to the infinite loop check.

**Comment by pamelafox** [comment]
This is same issue as:
https://github.com/Khan/live-editor/issues/260

John looked into and found it had to do with tab switching as well.  I put some ideas there. I'll close this one.
