### ISSUE TITLE
getImage() reports that it takes 0 parameters, in some browsers

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#339]
Reported on ZenDesk.

I haven't managed to replicate, but a user reports that on both his Chrome/Windows and Chrome/Mac, the getImage() function reports that it takes "0 parameters, not 1". I've attached the screenshot of that.

That error is based on babyhint extracting information from the global environment. We could add getImage to functionParamCount to just hard-code it to 1, so that there's no confusion.

![getimage](https://cloud.githubusercontent.com/assets/297042/8499596/d10d568a-2151-11e5-8b84-8f4bba7957cf.png)

**Comment by kevinb7** [comment]
I think hard coding is an easy solution to this issue.
