### ISSUE TITLE
add test/sample programs that people can use to do some manual testing

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/live-editor#360]
Rationale:
- some bugs are hard to create test cases for
- it's a good idea to do experimental testing so let's have some easy to access code to do that testing on
- could create tests that load programs from sample files and check that they run

**Comment by Cis112233** [comment]
Has this been done?

**Comment by kevinbarabash** [comment]
Yes it is.  Thanks!

**Comment by MikaalSky** [comment]
Since tests just run the code and check for errors, couldn't we put some complex programs that break often in the tests?
Not sure how tests work, just so ya know.

**Comment by kevinbarabash** [comment]
I tried automate the process using the current test infrastructure, but running longer programs takes more memory and after running 10+ different long programs in a row the tests started timing out.  Ideally, we'd spin up a new phantomjs instance when running each of these complex programs.  For now at least contributors will be able to more easily test changes to live-editor against real world programs.
