### ISSUE TITLE
replace jshint errors with BabyHint errors on the same line

### ISSUE THREAD

**Issue by kevinb7** [Khan/live-editor#361]
The following examples produces 5 errors:
```
fill(255, 0 0);
```
The first error which is the BabyHint error is the one that makes the most sense:
- Did you forget to add a comma between two parameters? (good)
- I thought you were going to type `)` but you typed `0`.
- It looks like you're missing a semicolon.
- I thought you were going to type an identifier but you typed `)`.
- I thought you were going to type an assignment or function call but you typed an expression instead.

**Comment by MikaalSky** [comment]
I think if babyhints throwing errors, we should ignore JSHint since it seems to freak out about babyhint things. Not completely ignore, just a ignore in the error region?

**Comment by kevinb7** [comment]
> Not completely ignore, just a ignore in the error region?

Yup, that's exactly what I'm proposing.

**Comment by MikaalSky** [comment]
Yeah. I've seen tons of help requests because people don't understand why there are so many errors when they made a simple typo.

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/live-editor/commit/41218aa73865407b74cc3b926aa9eca94156bb43.
