### ISSUE TITLE
Program embed code doesn't work in Firefox

### ISSUE THREAD

**Issue by Gigabyte-Giant** [Khan/live-editor#362]
This was originally found by Team Delta while we were working on KACJS.

A bit more information might be found at https://github.com/Team-Delta-KA/KA-Contest-Judging-System/issues/14.

Is there a known workaround for this problem (besides using Google Chrome)?

**Comment by Noble-Mushtak** [comment]
The following data link using KA's embed code works in Firefox for me: data:text/html,<h2><a href="https://www.khanacademy.org/computer-programming/what-is-it-adjustable/4857201710727168">What is it? (adjustable)</a></h2> <script src="https://www.khanacademy.org/computer-programming/what-is-it-adjustable/4857201710727168/embed.js?editor=yes&amp;buttons=yes&amp;author=yes&amp;embed=yes"></script> <p>Made using: <a href="http://www.khanacademy.org/computer-programming">Khan Academy Computer Science</a>.</p>

What specifically are you doing to the above code?

**Comment by Noble-Mushtak** [comment]
OK, sorry, this was before I saw the changes to `entry.js` and our embed code. I'll look into this, but I think this is a problem with us since the above data:text/html link is working. (NOTE: Refresh the page to see updated comment of data:text/html link.)

**Comment by Gigabyte-Giant** [comment]
I skip the `script` step, and move straight into the `iframe` step... Please see `entry.js` in the repository.

**Comment by Noble-Mushtak** [comment]
Wait...It's clearly working on Firefox for me. I can toggle the code and interact and everything. I'm running Ubuntu, so maybe this is a Firefox+Macs problem?

**Comment by Gigabyte-Giant** [comment]
No, because I tested it on Firefox w/ Windows.

**Comment by Noble-Mushtak** [comment]
Hm...That's interesting, concerning, and very odd.

**Comment by kevinb7** [comment]
I remember reading something about a particular callback not being fired for embedded programs, but I think that issue's been around for a while.  Is this a relatively new development.  What version of Firefox/Windows is this happening on?  Are there any messages in the dev console?

**Comment by Gigabyte-Giant** [comment]
In Firefox it says "`KAdefine` is not defined.". I'm using Firefox 39 on Windows 10 Technical Preview.

**Comment by JavascriptFTW** [comment]
I'm using Firefox 39.0 on Windows 8.1. Nothing comes up on the dev console that shouldn't, all that's there is the stuff that we're printing and the scratchpad initiation stuff (i.e. "Sound Manager loaded..."). No errors for me at least.

**Comment by kevinb7** [comment]
@Gigabyte-Giant this is really helpful.  Thanks for the report.

**Comment by SpongeJr** [comment]
Embedding a project seems to work fine for me with Firefox 39 and Windows 7. No issues, no console messages of note.

**Comment by kevinb7** [comment]
I though I opened a issue for this on our internal tracker, but I guess I didn't.  Doing that now....okay, done.

**Comment by Gigabyte-Giant** [comment]
...interesting, this issue isn't surfacing itself anymore.

Firefox 39 on Windows 10 Pro.

**Comment by kevinb7** [comment]
@Gigabyte-Giant glad to see it go away.  Thanks for closing this.
