### ISSUE TITLE
KAInfiniteLoopSetTimeout is not defined

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#363]
I had this code in a new program:
http://pastebin.com/sLz7Qdps
I tabbed out, moved around, then deleted the entireity of the program. An error was thrown all of the sudden:
![Screenshot](http://i.imgur.com/78YsLWc.png)

**Comment by pamelafox** [comment]
Yep, @kevinb is on it.

**Comment by MikaalSky** [comment]
@pamelafox Great!

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/live-editor/commit/6a83889e3181e1623c833fe3ae3ed16270995629.
