### ISSUE TITLE
/new/pjs doesn't always auto-save

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#376]
Discovered this when I lost an hour or two of hard work.
Progress vanished due to failed auto-save.

**Comment by kevinb7** [comment]
Sorry that you lost a sizable chunk of work.  Implementing auto-save is definitely on our radar, but I'm not sure when we'll get to it.

**Comment by MikaalSky** [comment]
/new/pjs is supposed to have autosaving to local storage.

**Comment by pamelafox** [comment]
The current auto-save  for /new only saves upon page navigation change- it doesn't save on a timer. I have an issue noted internally about that. I'll close this issue, since it wouldn't be implemented in live-editor.
