### ISSUE TITLE
Add samples programs for exploratory testing

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/live-editor#389]
Some possibilities:
- https://www.khanacademy.org/computer-programming/minecraft-ke-more-noise/5971033575129088
- https://www.khanacademy.org/computer-programming/rotate-this/6375407836200960

**Comment by kevinb7** [comment]
towers of hanoi:
- https://www.khanacademy.org/computer-programming/program/4772835774169088

**Comment by kevinbarabash** [comment]
Added by https://github.com/Khan/live-editor/commit/2c013923595f743f17da89dcce67dfc2a8aba762.  You can load all of the "pjs" code from all of the tutorials (talk-throughs), challenges, and official scratchpads by opening demos/simple/scratchpads.html and click on one of the many links.
