### ISSUE TITLE
Doing for (key in obj) gives undefined for each key in the PJS environment

### ISSUE THREAD

**Issue by kevinb7** [Khan/live-editor#395]
Calling ```walkAST(ast, null, [ASTTransforms.rewriteContextVariables(envName, context)]);``` with the AST for the following code
```
var obj = {
    x:5,
    y:10
};

for (var i in obj) {
    println(i);
}
```
generates the following output (after codegen):
```__env__168037363.KAInfiniteLoopSetTimeout(2000);
__env__168037363.obj = {
    x: 5,
    y: 10
};
for (var i in __env__168037363.obj) {
    __env__168037363.println(__env__168037363.i);
}
__env__168037363.KAInfiniteLoopSetTimeout(500);
```

The variable declaration in the for-in loop should've been converted to ```__env__168037363.i```, but it's not.

@Gigabyte-Giant you might want to give this one a try.

**Comment by Gigabyte-Giant** [comment]
I'm definitely going to do this one! :)

**Comment by kevinb7** [comment]
@Gigabyte-Giant cool.  Since this is a regression it would be nice to take care of this relatively quickly.  If you can't work on this soonish please let me know.
