### ISSUE TITLE
links with href='javascript:void(0)' should not open a new page

### ISSUE THREAD

**Issue by kevinb7** [Khan/live-editor#401]
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>New Webpage</title>
    </head>
    <body>
        <a href="javascript:void(0);" onclick="alert('hello');">click me</a>
    </body>
</html>
```
Click the link.  It will open `computer-programming/link_redirector?url=javascript%3Avoid(0)%3B` in a new tab and the page will say: `A webpage created on Khan Academy wants you to visit: javascript:void(0); Please click the link if you'd like to go there, otherwise close this window.
`

**Comment by pamelafox** [comment]
/ cc @jjwon
