### ISSUE TITLE
Allow links with protocol-relative URLs

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#402]
Reported on ZenDesk.

"Webpages that use <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> throw an error: The <script> tag's src attribute points to an invalid URL. Did you include the protocol (http:// or https://)?"

**Comment by MatthiasSaihttam** [comment]
This appears to have been fixed and merged, should it be closed?

**Comment by kevinbarabash** [comment]
@MatthiasSaihttam thanks for picking up these.  I merged some changes and never got around to deploying and then someone else deployed but didn't know about these github issues.
