### ISSUE TITLE
PLEASE stop surfacing invalid url errors with a fatal error.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#404]
It's not neccasary for a webpage to function for it to have valid urls. These should be dealt with like warnings, not errors.

**Comment by pamelafox** [comment]
/ cc @jjwon 

Can we handle them like we handle the image picker bad URL errors?

**Comment by MikaalSky** [comment]
Don't those prevent the user from continuing?

**Comment by pamelafox** [comment]
Ah-- I don't think they did before, they seem to now.

**Comment by pamelafox** [comment]
I'd suggest experimenting with adding a warning icon to the gutter for that line, and using the hover to give the information about validity.

**Comment by MikaalSky** [comment]
That might be a more new_error_experience thing. It might make sense to be able to dismiss error buddy for now.

**Comment by MikaalSky** [comment]
How about a more IDE way of surfacing errors (inline error reports with an error/warning list below, plus gutter icons like you mentioned)

**Comment by MikaalSky** [comment]
Nevermind, now that I reread thats what you were suggesting.

**Comment by jjwon** [comment]
I can work on adding something like that: in the meanwhile, should we revert the INVALID_URL error?  I can submit a PR or someone else can just push to master but all you'd need to do is comment out the code in `slowparse.js`.

**Comment by kevinb7** [comment]
On top of surfacing non-fatal warnings we might always want to have an actual error when someone clicks on the link.  This could be separate from the gutter warning.  In the meantime, @jjwon if you could submit a PR with the necessary line(s) commented out that would be much appreciated.

**Comment by MikaalSky** [comment]
Why not just floating error bubbles

**Comment by kevinb7** [comment]
In the editor or above the link in the output frame?

**Comment by MikaalSky** [comment]
Editor

**Comment by kevinb7** [comment]
That would work too, but there would be more engineering effort required.  The nice thing about the gutter warnings is that they're already supported by ace.  The downside is that they're hidden so there's no guarantee that a user will look at them.

**Comment by MikaalSky** [comment]
Just noticed.
We're on issue 404 and we're talking about the webpage enviorment. Links, specifically.

**Comment by kevinb7** [comment]
I've deployed @jjwon's change.  Please continue the conversation in https://github.com/Khan/live-editor/issues/406.
