### ISSUE TITLE
Determine how to surface invalid URLs

### ISSUE THREAD

**Issue by kevinb7** [Khan/live-editor#406]
Original issue: https://github.com/Khan/live-editor/issues/404

TL;DR: URLs without the http:// or https:// don't go where user's expect, e.g. `<a href="google.com">` redirects to an ka.org page that doesn't exist.  Popping up error buddy for this kind of issue is annoying because the rest of the webpage will still work.

**Comment by MikaalSky** [comment]
It's easy enough to just append the protocol. Browsers will autodetect if it's http or https anyway.

**Comment by kevinb7** [comment]
I believe browsers only autodetect if you type the URL into the address bar.

**Comment by MikaalSky** [comment]
No, just having a terminalbit.com href redirects to http://terminalbit.com

**Comment by kevinb7** [comment]
I must be doing something wrong.  When I add `<a href="google.com">Google</a>` to a page and click on it does not redirect for me, e.g. <a href="google.com">Google</a>

**Comment by kevinb7** [comment]
@MikaalSky which browser are you using?  I'm using Chrome and the link in the last post shows the github 404 page.

**Comment by jjwon** [comment]
It only works automatically appends the protocol if you type it into the URL bar, as Kevin said.  HTML tags `href`, `src`, etc do not append this by default.

**Comment by jjwon** [comment]
I was investigating a solution using the gutter annotations, as someone brought up in the other thread, and I think I have an idea of how to approach it.  Right now, the webpage output doesn't have support for this, but it's pretty similar to the way the PJS output does it.

Slowparse can throw warnings as well as errors, and I think we can just make use of this in the gutter.  This could also be a useful feature to lead students away from using more deprecated tags which will still render, or other bad/insecure habits.

**Comment by MikaalSky** [comment]
We might as well automatically append protocols if there isn't already one.

**Comment by pamelafox** [comment]
I don't want to do too much magical fixing, as then students will be handicapped when they get to other HTML editing environments and don't have that fixing tool. I like the idea of using the gutter for warnings, as there are a lot of other things in HTML that we might want to warn about and not error about.

**Comment by MikaalSky** [comment]
Autofixing with a warning at least, or just warnings. Not sure.

**Comment by kevinb7** [comment]
Let's start with gutter warnings and see how that goes.

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/live-editor/issues/403.
