### ISSUE TITLE
Calling functions declared in switch/case statements don't work in live-editor

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/live-editor#407]
Example: https://www.khanacademy.org/computer-programming/bug-function-definition-within-case-hangs-system/6101856746078208

@Gigabyte-Giant you may be interested in looking at this one.  It's another AST transform related bug.

**Comment by Gigabyte-Giant** [comment]
Adding this to my to-do list! :)

**Comment by Gigabyte-Giant** [comment]
@kevinbarabash I finally got around to looking at this, and I [submitted a PR](https://github.com/Khan/live-editor/issues/430) a bit ago.

**Comment by kevinbarabash** [comment]
@Gigabyte-Giant I'm going to try to review it today or this weekend at the latest.  Thanks for the PR.

**Comment by Gigabyte-Giant** [comment]
Don't worry, I'm not in any hurry to get it merged, just thought I'd go ahead and try and knock this one off my to-do list.

Have a nice weekend.
