### ISSUE TITLE
Unexpected Error In Program Using `debug`

### ISSUE THREAD

**Issue by JavascriptFTW** [Khan/live-editor#414]
Recently while attempting to view a program featured on the hot list (https://www.khanacademy.org/computer-programming/3d-much-whee/5008266156441600) I encountered an unexpected error
`__env__628994570.debug is not a function`
The only occurrence of a call to debug I found was on line 120 in the catch section of a try-catch statement. Attempting to use a debug statement in a separate program resulted in the expected behavior, but neither clear cache reloading nor pasting the code into a separate program eliminated the error.
I used debug in a separate program (https://www.khanacademy.org/computer-programming/new-program/4836532149157888) and it seems to work outside of a try-catch statement but not inside.

**Comment by Gigabyte-Giant** [comment]
...what browser are you using? I don't experience this problem on Chrome 44.0.2403.157 (OS is OS X Yosemite)...

The `__env__` prefix gets added during the AST transforms, which is one of my favorite parts of the live editor, so if the problem persists, I'll look into a fix.

**Comment by JavascriptFTW** [comment]
Sorry. I'm using Chrome 44.0.2403.157 m on Windows 10

**Comment by Gigabyte-Giant** [comment]
Interesting, I just went to DYs 3D program (which you linked to in the OP), and I **do** see the issue surfacing.

In your test program, it works just fine for me...

**Comment by kevinb7** [comment]
Setting `optimizeRestarts = false` fixes this issue.  This bug should be fixed with a change I'm rolling out tomorrow that also fixes https://github.com/Khan/live-editor/issues/413.

**Comment by Gigabyte-Giant** [comment]
Yep, I noticed that @kevinb7...

I'll keep an eye out for the change, as I'm interested to see what all went into these fixes.

**Comment by kevinb7** [comment]
@Gigabyte-Giant this has been fixed by https://github.com/Khan/live-editor/commit/81f67402f1ed1694e023fe950254396bdc01de45.
