### ISSUE TITLE
Add a warning about extra space in rgb ()

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#425]
Observed at workshop this weekend.

Some students write rgb (), with a space between rgb and the parentheses, which does not work.
They could try to debug that in Chrome by seeing it's an improper property value, but most don't get that far.
We could add a gutter warning about it.

This is a similar issue to https://github.com/Khan/live-editor/issues/268

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/live-editor/pull/412.
