### ISSUE TITLE
"You have unsaved changes" doesn't appear when pasting and searching on chrome.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#428]
Lose work. :(

Pasting a word into the url bar and hitting enter doesn't warn about unsaved changes.

**Comment by MikaalSky** [comment]
Ooo. That might of been a bug.

**Comment by kevinbarabash** [comment]
I tried pasting a URL into the omnibar in Chrome and when I hit enter the warning about unsaved changes showed up.  I also tried pasting a word to do a search into the omnibar and same result.  What version of Chrome are you using?

**Comment by MikaalSky** [comment]
Latest. Found that the event must of been unbound or something.

**Comment by Gigabyte-Giant** [comment]
I tried this on the latest version of Chrome, and I'm not having any issues.

It doesn't matter what I do in the Omnibar; I always get the popup if I have unsaved changes...

**Comment by MikaalSky** [comment]
Well, I had the tab open for a while, had tabbed out a lot and stepped away a few times. Not sure if that has anything to do with it.

**Comment by Gigabyte-Giant** [comment]
This kind-of sounds like a [browserbug](https://github.com/Khan/live-editor/labels/browserbug)...

I'll open one of my Khan Academy programs, make some changes, and leave it there for a couple hours, while going about my regular day; to see if I can replicate what you've described.

Is this the first time this has affected you, or has it happened before?

**Comment by MikaalSky** [comment]
This is the first time.

**Comment by Gigabyte-Giant** [comment]
...after 4 hours, I still do not have this problem.

**Comment by MikaalSky** [comment]
Not happening any more. Idk, might of been a huge explosion on my side.
