### ISSUE TITLE
Live updating not updating for program with mouseClicked

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#431]
Discovered during workshop

Steps to replicate:
1. Open https://www.khanacademy.org/computer-programming/project-interactive-diagram/6179666102714368
2. Change x position with number scrubber
4. Notice that it does not update the rectangle position
5. Now rename mouseClicked to 'var mouseClicked2', and repeat. Notice it *does* update rectangle position.

**Comment by kevinbarabash** [comment]
I'm not sure what I did, but this is fixed on the breakout_code_injector branch.

**Comment by pamelafox** [comment]
It looks like you merged it and fixed that issue, but I ran into a related issue in my sister's program here:
https://www.khanacademy.org/computer-programming/arc-issue/6596842260922368
Try changing a number in the arc() at the bottom- notice that it disappears until you restart it. If you comment out mouseClicked, it updates as expected.

**Comment by kevinbarabash** [comment]
@pamelafox I looked into the arc issue and it's actually a separate issue.  See https://github.com/Khan/live-editor/issues/506.  I'm going to close this issue because it appears to be fixed.
