### ISSUE TITLE
Warn Against use of Obsolete HTML Tags in the Webpage Environment

### ISSUE THREAD

**Issue by JavascriptFTW** [Khan/live-editor#434]
Browsing around the Khan Academy Computer Science section I've noticed that quite a few students are using obsolete HTML tags in their webpages (specifically `marquee` tags). While these tags may work and produce the desired effects students should be warned that these tags should not be used and can have unintended side effects.

**Comment by pamelafox** [comment]
I'll admit that I sometimes use <marquee> because its so darn fun. But yes, for tags that are truly deprecated like <marquee>, it'd make sense to add a gutter warning (not an Oh Noes).

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/live-editor/pull/435.

**Comment by DozenalFTW** [comment]
I know this is old, but @pamelafox , your HTML tags got snipped by GitHub. I take it the post said:
```
I'll admit that I sometimes use <marquee> because its so darn fun. But yes, for tags that are truly deprecated like <center>, it'd make sense to add a gutter warning (not an Oh Noes).
```
I only picked `<center>` as the guess because W3Schools says it's not supported in HTML5.
