### ISSUE TITLE
Possible bug with transformation matrix when updating realtime code

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#437]
Peter put together this demo based on a student's help request:
https://www.khanacademy.org/computer-programming/strange-system-bug-version-2/5457874696929280

He noticed that when you press enter, the vortex moves to a new location. The transformation matrix seems to change each time. Theoretically, it should either change upon each frame or never, not just when pressing enter... I think?

I could use insight of folks that have used the transformation functions on this issue.

**Comment by kevinbarabash** [comment]
It's an issue with the program.  The transform isn't being reset so we keep translating.  The reason why the triangles aren't translated off the page is because an interaction with rotate which moves things back on to the page.  Here's an improved version of the program that doesn't have the issue.

```
var face = 4;

var vortex = function(x,y) {
    translate(x, y); ///placement
    for (var i = 399; i > 209; i -= 0.5) {
        triangle(140, 18, 96, 5, 159, 99);
        rotate(face);
        face += 0.1;
    }
    resetMatrix(-x,-y);   // reset both the translate and the rotation
}; //vortex


var draw = function() {
    var y = 204;
    var x = 199;
    background(255, 255, 255);
    vortex(x,y);

};// end draw
```
