### ISSUE TITLE
Light-grey overlay is shown while a talk-through is playing

### ISSUE THREAD

**Issue by Gigabyte-Giant** [Khan/live-editor#451]
...the same overlay that gets shown when the Big [Error] Buddy is opened:

![overlay-prob1](https://cloud.githubusercontent.com/assets/4977819/10556857/a2d25eba-7457-11e5-8775-6b630934a87d.png)

The overlay isn't just when there's an error, it's all the time.

Google Chrome 46.0.2490.71 on Mac OS X El Capitan.

**Comment by pamelafox** [comment]
Ah, it's related to the fact that you're being served the
new_error_experience all the time, interesting. (Doesn't happen for the old
oh noes). I'll take a look at that on Monday.

**Comment by pamelafox** [comment]
Fixed

**Comment by Gigabyte-Giant** [comment]
Confirmed. Thanks!
