### ISSUE TITLE
For some reason, I'm not seeing the new_error_experience?

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#456]
This is probably something related to Khan and my account but for some reason I am unable to see the new error experience without the url parameter.
![Screenshot](http://take.ms/VJNiw)
With the parameter it works fine.
The reason why I think this is weird is because I've seen other people logged in with the new error buddy on by default.

**Comment by pamelafox** [comment]
We are only serving it to 10% of users by default right now, while I monitor the usage. You'll need to use the URL parameter if you'd like it all the time, as you're in the 90%.

**Comment by MikaalSky** [comment]
@pamelafox Ah, didn't know that. No problem.
