### ISSUE TITLE
Programs "Taking too long" instantly now.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#458]
![Example](http://take.ms/KuCeO)
Programs that worked fine are now just dying right away before they even get a chance to execute. Not sure the cause.

**Comment by pamelafox** [comment]
https://www.khanacademy.org/computer-programming/minecraft-ke-noise-bedrock/5971033575129088

@kevinbarabash  Yesterday's deploy included your injector change, so probably related to that?

**Comment by kevinbarabash** [comment]
Yikes!  I will have a look into it this weekend.

**Comment by kevinbarabash** [comment]
It works alright on my machine, but it could freeze up on slower machines.  @MikaalSky what are you running it on?

**Comment by MikaalSky** [comment]
@kevinbarabash i3 2.67 GHz I believe. Locks up on every machine I try which is unacceptible because it worked on chromebooks before.

**Comment by alexristich** [comment]
I can confirm it's the same problem for me on a i5 1.8GHz 2012 MBA.

**Comment by MikaalSky** [comment]
It seems to be happening to most problems with a lot of for loops.

**Comment by MikaalSky** [comment]
Programs***
Github for mobile.

**Comment by Gigabyte-Giant** [comment]
I can also confirm that this is occurring on my machine.

Processor: 3.2GHz i5
16GB of RAM

**Comment by Potato42** [comment]
Doesn't always happen instantly.  Programs such as [this one](https://www.khanacademy.org/computer-programming/bouncing-on-the-sky/6681224671133696) work fine for a while, then "take too long".

**Comment by kevinbarabash** [comment]
I've got much trust MBA out have been able to repro the issue.

**Comment by IndieKA** [comment]
MikaalSky, you went to GitHub? So you practically left KA for GitHub. Wise choice.

**Comment by MikaalSky** [comment]
@IndieKA Please don't talk about that here.

**Comment by IndieKA** [comment]
@MikaalSky Sorry, just needed some way to talk to you. I'll delete my comment.

**Comment by kevinbarabash** [comment]
This is fixed by https://github.com/Khan/live-editor/commit/ac06ee7d50cc6d0d8c48e665760911001f3b4ffd
