### ISSUE TITLE
Modal dialogs in iframe and CSP

### ISSUE THREAD

**Issue by SpongeJr** [Khan/live-editor#467]
We used to be able to use alert() and other modal dialog boxes and such. Now we see messages along the lines of: `Ignored call to 'alert()'. The document is sandboxed, and the 'allow-modals' keyword is not set.` in Chrome, but not Firefox.

I'm pretty sure it's due to this relatively new feature of Chrome:
https://www.chromestatus.com/feature/4747009953103872

Came across as a result of [this Help Request](https://www.khanacademy.org/computer-programming/my-blog/4576835499851776?qa_expand_key=kaencrypted_9e11f1baca23f635e3882bc50d18b8d3_6ae596f6cec3b8fbf48a932a11e29c6bef43dff2cb574a85dbf03f4470a5a04fd9b011ea7de0fdbf286b7c6a415cd0188195957320ee6453cc9dba9a828aa33a4cc1831b6ac12d95836f3b39384bc8a3ec20a5c28abf51b6a1b19b5e48270062e4441df0de3d125f18f6f4c5336b9479af30874d5c88554008b70d200c898f3c2098bc05fe0d6c1482e2054679f1390d6448d2b3b3b3c8a6412d1a7eb7a3e26e932bd6398971ddc85c6b7ff5f3998b209019f22ff5a1368b8c0de01cb7bdb72d)

There were issues with modals and the infinite loop checker, if they're used in places where that applies, and they could be used to slightly annoying effect, but I don't think they've ever been explicitly blocked in the webpage environment. Suggest they either be altogether blocked (with some feedback to the user as to why) or changing the CSP to add `allow-modals`. I haven't seen any serious issues with them, so it'd be nice have them allowed.

**Comment by kevinbarabash** [comment]
Thanks for the report.  Adding `allow-modals` to the CSP sounds like an easy fix.

**Comment by pamelafox** [comment]
To clarify, this isn't part of our CSP (which is set on the server), it's part of the <iframe sandbox> attributes (which are set in HTML). I'm making the change now.

**Comment by pamelafox** [comment]
Deployed!

**Comment by kevinbarabash** [comment]
Yay!
