### ISSUE TITLE
Support PGraphics

### ISSUE THREAD

**Issue by LoganDark2** [Khan/live-editor#470]
PGraphics are somehow unsupported, and I think they would be very useful. The problem is, the version of Processing.js is outdated, preventing us from using the newer features.

**Comment by kevinbarabash** [comment]
I would like to update processing.js, but haven't had time.  Also, our fork of processing.js has changes that would either need to be pushed upstream or ported to the newer version.

**Comment by LoganDark2** [comment]
Could you possibly add support for PGraphics? I need a way of displaying
multiple layers. Such as in my Draw+ program, I need a way of displaying
some sort of cursor while maintaining the image below. I have considered an
array of what has been drawn, but it would be too hard to implement.

If you can't add support for PGraphics, I would really love it if you did
update Processing.js.

>

**Comment by kevinbarabash** [comment]
You can use PGraphics.  Here's a code snippet that should work.  The third argument corresponds to the renderer.
```
var g = createGraphics(100, 100, 4);

g.fill(255, 0, 0);
g.rect(0,0,50,50);
g.rect(50,50,50,50);

image(g, 100, 100);
```

**Comment by kevinbarabash** [comment]
@LoganDark2 have you tried the code I posted above?  If you need multiple layers, it might be easier to use to multiple canvas elements in webpage environment.  If it's just for a cursor you could also try using CSS custom cursors, see https://davidwalsh.name/css-custom-cursor.

**Comment by brew4321** [comment]
@kevinbarabash you can layer canvas elements? ..very interesting, I'll have to experiment with that. But another question, is there a reason not to implement support for PGraphics? Is it like a security issue?

**Comment by kevinbarabash** [comment]
@brew4321 from my understanding it is supported.  The code snippet in my previous comment should work.

**Comment by brew4321** [comment]
@kevinbarabash Oh my bad! Yes it works. I should know better, because I've used `createGraphics` extensively. But since we never have to write `PGraphics` I was confused thinking that was something else.

**Comment by GoToLoop** [comment]
> The third argument corresponds to the renderer.

Better use constants for renderer. JAVA2D for 2D or P3D for WebGL.

**Comment by kevinbarabash** [comment]
@brew4321 cool.  @GoToLoop thanks for looking up the constants.

**Comment by brew4321** [comment]
@GoToLoop do you know a good place were I can read about the trade offs of the various rendering options? For example I read here: http://processingjs.org/articles/RenderingModes.html that both P3D, and OPENGL use webgl, but I'm wondering if one uses it more efficiently than the other, because I'm sure I read somewhere that P2D is faster that JAVA2D... The article says, "Processing allows developers to choose renderers based on tradeoffs of speed and quality" but then I can't find any analysis of said tradeoffs... :S

**Comment by GoToLoop** [comment]
* All of those constants are used to describe the various renderers available for Processing's "Java Mode".
* However, both "JavaScript Mode" (a.K.a. ProcessingJS or PJS) and p5.js flavors got either 2D or WebGL canvas.
* In the end, both JAVA2D & P2D refers to regular 2D canvas.
* While OPENGL & P3D for the WebGL counterpart.  ;-)
