### ISSUE TITLE
throw functions not working

### ISSUE THREAD

**Issue by IndieKA** [Khan/live-editor#473]
Just so you know, the new error experience is not compatible with `throw();`
Plagiarism has become a big thing on Khan Academy, and some programmers use `throw();` to help protect their programs. Some other people use `throw();` to suggest bigger canvas sizes.

The following code is used by hundreds of users to defend what they have made.
```
var author = "thatGuy";
draw = function(){
if(author !== "thatGuy"){
throw {
message: "Don't copy!"
};
}
}
```

And use of punctuation nor use of just `throw();` does not work either. You should probably configure this before users start a petition.

**Comment by Gigabyte-Giant** [comment]
The New EB experience is compatible with `throw`, you just have to change your code a bit...

Here's an example:
```javascript
var criteria = "giga";

draw = function() {
    if (criteria !== "gigabytegiant") {
        throw({
            message: "Oh Noes! That's not Giga's full name!"
        });
    }
};
```

**Comment by IndieKA** [comment]
Ah, alright. Thanks. Mind closing this issue?

**Comment by Gigabyte-Giant** [comment]
I can only close my own issues, sorry. **You**, can close the issue, though. Just click the close button that is shown below the input area.

![close_issue](https://github-cloud.s3.amazonaws.com/assets%2F4977819%2F10957530%2Fc2ad45ba-832a-11e5-869d-3b07556b56f7.png)

**Comment by GoToLoop** [comment]
So that "fix" is based on adding up parentheses to `throw`'s expression parameter?
Just know that officially that's completely redundant: @_@
https://developer.Mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw
