### ISSUE TITLE
Show better answers/questions

### ISSUE THREAD

**Issue by IndieKA** [Khan/live-editor#476]
Not too long back I was viewing my profile from another account and I realized that only my answers/questions w/the most votes show up.

This is okay in some situations, but sometimes my short-length Q/A gets posted on my profile. You should make it so that the most detailed of someone's Q/A shows up on their profile. I don't want people to have first impressions, ya know.

**Comment by MikaalSky** [comment]
I know you posted this one earlier than the other, but the same applies to this. Not a live-editor issue.

**Comment by Gigabyte-Giant** [comment]
Just a heads up, the live-editor repository is for stuff relating to the live-editor project, not general Khan Academy things.

In the future, I'd recommend that you post stuff like this in the correct section on [Zendesk](https://khanacademy.zendesk.com/hc/en-us).

**Comment by IndieKA** [comment]
Sorry about that.
