### ISSUE TITLE
Why no "New Program" in programs section

### ISSUE THREAD

**Issue by IndieKA** [Khan/live-editor#477]
If you go to your profile, and then hit the 'Programs' tab you will see there is no more 'New Program' button anymore. I saw this change a while back but never really posted an issue about it. You might want to change that.

**Comment by MikaalSky** [comment]
Not related to the Live-Editor but still related to the programming section.
Just so ya know, anything not directing the editor should be reported via zendesk if it's an issue. If it's a suggestion, open up an idea in the support.
This will most likely get closed.

**Comment by IndieKA** [comment]
Hm, I'll close it then.
