### ISSUE TITLE
ctx.canvas externals no longer work

### ISSUE THREAD

**Issue by IndieKA** [Khan/live-editor#479]
The following program (https://www.khanacademy.org/computer-programming/stroke-text/1742701698) does not work anymore. Why? Khan Academy disabled programs w/`this.externals.canvas` and `var ctx = canvas.getContext("2d");`

Although this isn't allowed on KA, you might want to change that because some popular programs use `ctx` for better graphics.

**Comment by MikaalSky** [comment]
...Because it's externals and it should be blocked?

**Comment by IndieKA** [comment]
But what's wrong w/ctx?

**Comment by MikaalSky** [comment]
CTX requires use of externals to access so that's basically what's wrong.
Plus, you don't even need ctx, use the native methods and make something cool. ;)

**Comment by IndieKA** [comment]
Alright...
On the other hand, I don't mean to go offtopic, but is there a way to talk w/another user besides using issues?

**Comment by kevinbarabash** [comment]
@IndieKA https://gitter.im/Khan/live-editor.

If you want to use canvas directly then the webpage environment is your friend.

**Comment by IndieKA** [comment]
But Pamela is hardly on that... Nor someone else either, you're pretty much the only one and some others..

What's your Khan Academy account? Profile link?

**Comment by JavascriptFTW** [comment]
@IndieKA Just post a message on Gitter. It typically gives emails (at least to me) when there are new messages
