### ISSUE TITLE
New error experience makes OOP programs fixed 

### ISSUE THREAD

**Issue by IndieKA** [Khan/live-editor#480]
Just wanted to point this out, although this isn't a issue, the new error experience makes average programs that use OOP fixed. What I mean by this is usually if you changed something in a program that uses OOP something like "string is not a function" might come up. The new EB doesn't do that anymore.

**Comment by MikaalSky** [comment]
Would be more useful as a comment on a New Error Experience comment or a comment on a commit, but I guess this is okay.

**Comment by pamelafox** [comment]
Good to know, thanks!

**Comment by IndieKA** [comment]
Okay. Just saying!
I'm pretty happy now I got to talk w/Pamela.
