### ISSUE TITLE
Cursor type for number-scrubber isn't being updated properly

### ISSUE THREAD

**Issue by alexristich** [Khan/live-editor#485]
For the number-scrubber, when the user hovers over the left or the right arrow, the cursor should be changed to a pointer, but it stays as the `ew-resize` cursor.

The issue here is that the `tooltips.css` file only contains a relevant attribute selector in the case of structured-blocks. A new PR is coming momentarily with an added attribute selector for the standard case.

**Comment by kevinbarabash** [comment]
@alexristich can you post screenshots for UI bugs?

**Comment by alexristich** [comment]
Absolutely. Here's a quick screencast:
http://screencast.com/t/C2zBNVyNpyc

A screenshot is tricky for this one, since screenshots by default hide the cursor, though the screencast can be viewed in your browser and should give you a good sense of what this is referring to.

By the way, is the `.block` CSS class in `tooltips.css` actually being used at the moment?

**Comment by kevinbarabash** [comment]
> By the way, is the `.block` CSS class in `tooltips.css` actually being used at the moment?

It doesn't appear to be.

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/live-editor/pull/486.

**Comment by alexristich** [comment]
Good to know. I'll work around it in the meantime - the SVG wrt the number scrubber icons is next on my list.
