### ISSUE TITLE
Unhelpful Error Message When Using ES6/7 Features

### ISSUE THREAD

**Issue by JavascriptFTW** [Khan/live-editor#492]
The error message thrown by jshint when you attempt to use ES6/7 features in the live editor is "'some cool feature' is only available in JavaScript 1.7.". While this is an acceptable message it may not be the most helpful for some students.

**Comment by kevinbarabash** [comment]
Which features were you trying to use?

**Comment by kevinbarabash** [comment]
I tried using arrow function and saw the message.  I didn't realize we had these error messages.

**Comment by JavascriptFTW** [comment]
@kevinbarabash I tried to use "concise methods" (according to the error) i.e.
```
var ninja = {
    dance() {
        
    }
};
```

I believe that there was something else that I tried doing at some point that made the error come up as well.
