### ISSUE TITLE
Sudden problems with PVector method on new PVector objects.

### ISSUE THREAD

**Issue by brew4321** [Khan/live-editor#495]
This: https://www.khanacademy.org/computer-programming/pool-table/5599761850826752 program was on the hot list, and I know it used to work. And it hasn't been modified in two months, and yet it suddenly stopped working. Which I discovered when this: https://www.khanacademy.org/computer-programming/air-hockey-wip/5585122674475008 spin-off bugged out, and the person submitted a help request.
I've reduced the bug to this:
```var v1 = new PVector(0,0);
var v2 = new PVector(1,0);
var v3 = new PVector.sub(v1,v2);```
Which I believe is syntactically valid but it throws the same error.

**Comment by JavascriptFTW** [comment]
The problem here is that `PVector.sub` is not a constructor so the `new` is what's messing it up. If the `new` is removed the code should work as expected.

**Comment by GoToLoop** [comment]
More precisely, the static **sub()** method uses `new` internally. Then it stores the result in it.

**Comment by kevinbarabash** [comment]
Changing all `new PVector.sub()` commands to `PVector.sub()` fixes it.  It not sure how it could've worked the other way.  It's a pretty cool program.  @brew4321 can you let the creator know what the fix is?

**Comment by brew4321** [comment]
@kevinbarabash sure :)
