### ISSUE TITLE
Towers of Hanoi program no longer working

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#499]
The Towers of Hanoi program now results in an error "Cannot read property prototype of undefined":
https://www.khanacademy.org/computer-programming/program/4772835774169088

I haven't looked into yet, have to go somewhere now. If anyone beats me to investigating it, I won't mind. :)

**Comment by Gigabyte-Giant** [comment]
I'll take a look at this; I'm betting it has something to do with an AST transform...

**Comment by Gigabyte-Giant** [comment]
This is the same problem as https://github.com/Khan/live-editor/issues/496, which was fixed in https://github.com/Khan/live-editor/commit/f4e83d15eef408381c6b1a3a284efa855419b92f.

My apologies, once again.

**Comment by pamelafox** [comment]
Okay, I'll work on deploying that fix now. That's fine, the important thing is that we keep adding tests, which you did. Thanks for verifying its fixed in your branch.

**Comment by kevinbarabash** [comment]
We should add that program as a test case.  In fact it would be awesome had a regression suite that verified that all official scratchpads run without error.

**Comment by pamelafox** [comment]
Deployed!
