### ISSUE TITLE
tranform of NewExpressions where the contructor is a MemberExpression	fails

### ISSUE THREAD

**Issue by Gigabyte-Giant** [Khan/live-editor#504]
*Brought to my attention by @SpongeJr*.

See [this scratchpad](https://www.khanacademy.org/computer-programming/bug/4608920221515776).

I've already determined that the problem is caused by trying to declare new instances of the property of an object.

For example:
```javascript
var myObj = {};
myObj.myConstructor = function() {};

var myInstance = new myObj.myConstructor();
```

Once again, since I broke it, I'll fix it.

**Comment by MikaalSky** [comment]
First we plant the tree.
Then we jam a branch into the tree.
Later we cut off some of that branch and repot it.

Basically what that code is.
Good catch, though. Don't wanna confuse learners.

**Comment by Gigabyte-Giant** [comment]
Just in case anyone is wondering what's going wrong:

In [my AST transform](https://github.com/Khan/live-editor/blob/master/js/output/pjs/pjs-ast-transforms.js#L293-L316), my code is making the assumption that `node.callee` has a `name` property, which is not always the case.

I should have a fix ready to go in a bit.

**Comment by kevinbarabash** [comment]
@SpongeJr thanks for catching this.  @Gigabyte-Giant can you also check that `var name = 'b'; var c = new a[name]();` works as well?  An AST test isn't necessary for this b/c the program fails to run if the transform is incorrect, a regular `test` test should do the trick.

**Comment by Gigabyte-Giant** [comment]
Sure thing.

Just a heads up; the fix might be delayed a bit, as I'm really busy these days.

**Comment by MikaalSky** [comment]
Here's a living example of this. Below line 115.
[Game Engine that got broke](https://www.khanacademy.org/computer-programming/not-for-public-use/4643054469906432)

**Comment by MikaalSky** [comment]
Chrome, Windows error:
.toString() is undefined...
Firefox, Mac OS X Error:
e.value is undefined

**Comment by MikaalSky** [comment]
Huh, actually, it seems this isn't happening in the Live Editor Demo.
http://khan.github.io/live-editor/demos/simple/
Put the code from this program in it:
https://www.khanacademy.org/computer-programming/not-for-public-use/4643054469906432
It'll run on the demo but not the KA environment.

**Comment by Gigabyte-Giant** [comment]
I won't be submitting a fix for this issue, as I haven't found time to write one. Sorry.

**Comment by MikaalSky** [comment]
I'm gonna hop on board the Bug Fixing Boat and try to tackle this one.

**Comment by Gigabyte-Giant** [comment]
Good luck @MikaalSky. I think I've explained the issue to you well enough.

Here's a link that you'll want to save (originally shared with me by @pamelafox): http://esprima.org/demo/parse.html#

Throw some test code into it, and look at how the AST looks; from there, you should be able to figure out a good way to perform a node-rewrite.

Good luck, have fun, and happy learning!
