### ISSUE TITLE
`arc` is not a `safeCalls` but it should be

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/live-editor#506]
The problem is that we look at the source code for `arc` and see the it contains `p.convertToRadians(start)` and so we don't add it to `safeCalls`.  The thing is the neither `p.convertToRadians` nor `arc` change any state so it's actually okay for `arc` to be in `safeCalls`.

**Comment by pamelafox** [comment]
Sent a diff for this, thanks for figuring that out!
