### ISSUE TITLE
Clicking on an option in autocomplete dropdown doesn't actually select it

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#507]
I noticed this while watching my sister learn programming.

If you type strokeW, and then try to select strokeWeight, it doesn't actually replace it.
It only selects it if you use your keyboard, tab, and press enter.

Most new programmers aren't keyboard users like that however, so it is frustrating for them.

I'm not sure if click ever worked (i.e. if this is a regression) or if it was only ever keyboard-accessible.

**Comment by Gigabyte-Giant** [comment]
This is a duplicate of https://github.com/Khan/live-editor/issues/408.

**Comment by pamelafox** [comment]
Ahh, thanks, closing!
