### ISSUE TITLE
for() Infinite Loop, unhelpful error.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#522]
![Screenshot](http://take.ms/kD2wK)
[Program In Question](https://www.khanacademy.org/computer-programming/agario-singleplayer/5153226747412480)
Basically, I ran against the wall a whole bunch and what I'm assuming is the loop protector fired. It leaves behind a really unhelpful error.

**Comment by Gigabyte-Giant** [comment]
Duplicate of https://github.com/Khan/live-editor/issues/521.

**Comment by MikaalSky** [comment]
Partially #518 as well, but more specifically the message issue.

**Comment by kevinbarabash** [comment]
I think this is a duplicate of https://github.com/Khan/live-editor/issues/521, but since one has a nice screenshot I'll close the other as a duplicate of this.

**Comment by Gigabyte-Giant** [comment]
I decided to (try and) spread some holiday cheer, by creating a really inaccurate "snow simulation" using the Khan Academy PJS environment (don't worry, I'm making one for terminal as well).

The idea, is that snow (ellipses) fall down the canvas, and then stop once it hits the ground (the bottom of the canvas, minus an offset).

Here's the program: https://www.khanacademy.org/computer-programming/simple-snow/6509434456637440

After the program runs for a little while, I get the error that @MikaalSky reported...:
![snow1](https://cloud.githubusercontent.com/assets/4977819/11932669/c3475ec8-a7bc-11e5-9953-edb17a4aead2.png)

I'm sure I could resolve this problem by removing the "snowflakes" after they hit the bottom of the screen, but where's the fun in that?

**Comment by Potato42** [comment]
The specific line of code that is at fault here is probably https://github.com/Khan/live-editor/blob/d75ef52dc624ac62e64a169437d8169962927786/js/output/pjs/pjs-output.js#L492  
The callback assumes that the error will have an html property, but it actually has a infiniteLoopNodeType (or whatever it's called) property.

**Comment by kevinbarabash** [comment]
@Potato42 good detective work.  Would you be able to put together a pull request with the correct property?

**Comment by Potato42** [comment]
I've had bad luck in the past with the building process for live-editor PRs on windows.  I might consider trying again, but 
a) If I understand the problem correctly, it's a really simple fix for someone who isn't on windows and is more competent at git and build tools than I am.  Basically, just take the message from [here](https://github.com/Khan/live-editor/commit/57130931aa8ded361a081b7cfc803c3bf4d317e0#diff-239bd25a62930cb5a65b80f1b4edc53dL87508), and use  `LoopProtector.nodeMessages[error.infiniteLoopNodeType]` for the type.
b) I believe there is a better way to fix this bug which involves reverting the current XSS fix and simply adding an extra layer of kasandbox iframes for the editor and oh noes guy.  If you have access, see the continued discussion on the related hackerone thread for my reasoning behind this.

**Comment by benjaminjkraft** [comment]
I'm going to take a look at this while I'm looking at another related thing; not sure if I will get a chance to fix it, but if not I'll unassign myself so others can.

**Comment by benjaminjkraft** [comment]
I believe this was also fixed in d16b858 -- error-buddy now shows the location and a proper error message -- but I'm not entirely sure if I had a consistent repro of it in the first place.  Please feel free to reopen or make a new issue if this isn't actually fixed for you, and thanks for all the reports!
