### ISSUE TITLE
Khan SQL doesn't require the 'AS' keyword to do the same job as the 'AS' keyword

### ISSUE THREAD

**Issue by thomasmorelli** [Khan/live-editor#526]
![The 'AS' keyword is not required](https://cloud.githubusercontent.com/assets/16276687/11918116/e1f529fa-a71b-11e5-8eec-384761d29a8b.png)

I just stumbled across this bug where the 'AS' keyword is not required to change the column name from, say, ```SUM(words)``` to ```number```.

**Comment by pamelafox** [comment]
That's consistent with the SQlite demo, which is using the same library:
https://kripken.github.io/sql.js/GUI/

The SQLite diagram here seems to indicate the AS is optional in SQLite?
https://www.sqlite.org/syntax/result-column.html

**Comment by kevinbarabash** [comment]
According to http://savage.net.au/SQL/sql-99.bnf.html#as%20clause `AS` is option in an "as clause" in SQL99.  I'm closing this as a not a bug.
