### ISSUE TITLE
Unhelpful OhNoes error

### ISSUE THREAD

**Issue by thomasmorelli** [Khan/live-editor#527]
On https://www.khanacademy.org/computer-programming/jolly-mcfreezes-gingerbread-jubilee-wip/5706409032941568 I just noticed a very strange OhNoes error come up. 

![Unhelpful ohnoes error on DY's program](https://cloud.githubusercontent.com/assets/16276687/11918218/99f04dd4-a71f-11e5-9f05-4d2797be851a.png)

This may be related to #522, but as it doesn't look like a loop, I created a new issue here.

**Comment by thomasmorelli** [comment]
I've just checked DY's [3D Much Whee](https://www.khanacademy.org/computer-programming/3d-much-whee/5008266156441600) program. and it has the same unhelpful error - just in a different place.

The error on [3D Much Whee](https://www.khanacademy.org/computer-programming/3d-much-whee/5008266156441600) looks a lot more like #522, but I'm not sure. You can close this issue if it's a duplicate though!

![3D Much Whee OhNoes error](https://cloud.githubusercontent.com/assets/16276687/11918243/bfa524ea-a720-11e5-9125-75a76d60d7ab.png)

**Comment by kevinbarabash** [comment]
I'm going to close this as a duplicate.  I'll check that these programs work once we have a fix for https://github.com/Khan/live-editor/issues/522.
