### ISSUE TITLE
Lint error makes for a comatose program.

### ISSUE THREAD

**Issue by lgto4** [Khan/live-editor#528]
See the program at https://www.khanacademy.org/computer-programming/wat5/5754244333961216 

A syntax error (?) is not flagged by Yoko Oh Noes and the program appears comatose (since it is not run).

**Comment by kevinbarabash** [comment]
This isn't a syntax error b/c `a = [,];` evaluates to `[undefined x 1]` in the Chrome dev console and jshint.com produces a warning but no syntax error.  Not sure why the program doesn't run.  My guess is maybe an issue with the AST transforms.

**Comment by lgto4** [comment]
Yes.  I should have said "lint", not "syntax".
