### ISSUE TITLE
Number-scrubber can go way off the editor

### ISSUE THREAD

**Issue by thomasmorelli** [Khan/live-editor#531]
Number-scrubber going off way too far to the left
![Number-scrubber goes off way too far to the left](https://cloud.githubusercontent.com/assets/16276687/12070684/1028f7ca-b07c-11e5-9c61-c03baadedfca.png)

Number-scrubber can go on forever to the right:
![Number-scrubber can go on forever to the right](https://cloud.githubusercontent.com/assets/16276687/12070682/07b6991c-b07c-11e5-9bc1-8162690097ed.png)

I just came across this bug with the number-scrubber where it can go on way too far to the left, or forever to the right.

This bug is not a language-specific bug, it can be replicated in PJS, HTML (if you include a number, e.g. ```<p id="3"></p>```) and SQLite.

I have tested this on a Chromebook and a Windows 10 PC, so I don't know (but I am fairly sure) that it can be replicated on a Mac.

Maybe you could limit the number-scrubber to inside the editor?

I'm afraid I can't put together a pull request as I've yet to learn how full JS works.
Thanks!

**Comment by darrylyeo** [comment]
I can't say for sure, but I think this was part of the design. It seems odd at first, but at the same time it doesn't make sense to arbitrarily stop the scrubber once it reaches the edge of the ACE editor. That would make for a potentially jarring experience.

On a different note (and we can see it in your screenshot), the width of the scrubber seems to limit itself when scrolled past the right side of the window, causing the arrows to wrap.

**Comment by kevinbarabash** [comment]
I agree with @darrylyeo.  That being said, it would be nice if the scrubber didn't collapse we it reached the right side of the screen.  That should be a relatively easy fix by setting a a fixed width on the scrubber.

**Comment by darrylyeo** [comment]
Should I start a new issue for that, @kevinbarabash?

**Comment by kevinbarabash** [comment]
@darrylyeo sure.  I'll close this one.
