### ISSUE TITLE
Canvas size picker is non-functional in/on webpage environment

### ISSUE THREAD

**Issue by Gigabyte-Giant** [Khan/live-editor#532]
I realize the "canvas size picker" is a new feature, but there are a few problems with it, mainly in the webpage environment.

First off, it's not actually showing the default "canvas" size when you open it; it shows 400x400, which is the default for the PJS environment, but not the webpage environment.

Secondly, picked sizes do not appear to be saved after applying. They're there for the remainder of the "session", but as soon as you navigate away from the page and back, the canvas size does not appear as it should.

My hypothesis, is that the webpage environment isn't "acknowledging" custom canvas sizes when it loads.

If you visit [this](https://www.khanacademy.org/computer-programming/rush-lyrics/6479329864843264) webpage, you'll notice that the webpage appears in the default webpage size.

This shouldn't be the case, as I set the width (using the picker), to 500. That can be proved by viewing the JSON response from a [call to the scratchpad API for this webpage](https://www.khanacademy.org/api/internal/scratchpads/6479329864843264) (pay close attention to the `width` property).

This is über-low priority, but it's not un-important enough to go without a report.

**Comment by kevinbarabash** [comment]
The webpage size is resizable using by dragging the divider.  I think the "canvas" size options were meant for the pjs environment.

**Comment by Gigabyte-Giant** [comment]
I realize that, yes. That being said, I believe that if a control of that nature is on the page, it should be functional.

Feel free to close this if you don't think my concerns are valid!

**Comment by kevinbarabash** [comment]
@Gigabyte-Giant I think this report is totally valid.  In terms of resolution though, hiding the controls for non-PJS environments is probably the route to go.  I should've said that in my previous comment.

**Comment by Gigabyte-Giant** [comment]
Glad to hear we're on the same page. Hiding the controls was one of my first thoughts.

**Comment by pamelafox** [comment]
I have a task internally reminding me to do this (as this came up in the tips/thanks of the release program). It's an internal change, so I'll close it here. Thanks!

**Comment by Gigabyte-Giant** [comment]
I figured there'd be something already listed internally. Thanks @pamelafox.

**Comment by DozenalFTW** [comment]
Who opened this issue?

Well, in that case, I think setting a default of 400 for webpages can be allowed — but the user still can resize them. And what about the height?

**Comment by MikaalSky** [comment]
@dozenalFTW Look at the OP for that info.
