### ISSUE TITLE
Idea: GETDATE() in SQL?

### ISSUE THREAD

**Issue by thomasmorelli** [Khan/live-editor#534]
Could this be a possibility?

I got the idea from [this page](http://www.w3schools.com/sql/func_getdate.asp)

**Comment by Gigabyte-Giant** [comment]
Have you reviewed [this](https://www.sqlite.org/lang_datefunc.html) page?

**Comment by thomasmorelli** [comment]
@Gigabyte-Giant Sorry, I was looking in the wrong place again! I'll close this

**Comment by thomasmorelli** [comment]
Sorry, I was looking in the wrong place. I'm going to close this.
