### ISSUE TITLE
No description for bezierVertex error

### ISSUE THREAD

**Issue by Eytukan** [Khan/live-editor#536]
I was coding today and made a mistake in my code. I didn't put a vertex in front of my bezierVertex. Obviously I should've known that but I ran into an error buddy which showed nothing and gave no description on how to reverse this.

Shows how the error occurs:
https://www.khanacademy.org/computer-programming/~/4816748243451904

**Comment by kevinbarabash** [comment]
@Eytukan unfortunately the error buddy isn't very good at reporting runtime errors.  At the very lease we should have some kind of a message like "Oh noes!  A error occurred while running your program".

**Comment by Eytukan** [comment]
that would be just fine. I just wasn't able to understand what my problem was until much later
