### ISSUE TITLE
Number scrubber shrinks width when scrolled past right side of window

### ISSUE THREAD

**Issue by darrylyeo** [Khan/live-editor#544]
The number scrubber shrinks its width when scrolled past the right side of the window, causing the arrows to wrap. (Screenshot by @thomasmorelli)
![image](https://cloud.githubusercontent.com/assets/16276687/12070682/07b6991c-b07c-11e5-9bc1-8162690097ed.png)

I'd go a little further to suggest replacing the scrubber with an SVG graphic so we can ensure a consistent look and feel across browsers and operating systems. It's not good to rely on inline Unicode shapes.

**Comment by DozenalFTW** [comment]
**Support**

**Comment by kevinbarabash** [comment]
I like the SVG suggestion.

**Comment by kevinbarabash** [comment]
Resolved by https://github.com/Khan/live-editor/pull/593
