### ISSUE TITLE
Making an image via get() causes near comatose editor

### ISSUE THREAD

**Issue by lgto4** [Khan/live-editor#554]
See the simple demo at [https://www.khanacademy.org/computer-programming/wat8/5444735399755776].  The program is nearly uneditable or Restartable... until you remove the `get` invocation.

**Comment by Potato42** [comment]
Not sure what you're talking about here...  The editor works fine for me on that program.

**Comment by lgto4** [comment]
I just tried it again.  As you observed, all seems fine with my Firefox browser.  My Google Chrome browser still takes forever (say) to change the background color to yellow and then to green.

**Comment by Potato42** [comment]
Huh, you're right.  In Firefox it works fine for me, but in Chrome it is quite slow.  My unsubstantiated guess is that has to do with the implementation of get in processing.js instead of the live-editor though.

**Comment by lgto4** [comment]
Assigning blame is always hard.  I just picked the largest target.

**Comment by Potato42** [comment]
Yeah, I just [looked into](https://www.khanacademy.org/computer-programming/get-timer/5272529583603712) this issue some more and it's pretty weird.  There does not seem to be a significant performance difference with `get` itself between FF and Chrome.  Simply calling `get` somewhere doesn't freeze up the editor, but calling it in combination with a draw function _does_.  Even with the draw function, `get` itself is not slow, the editor just freezes up.

**Comment by Cis112233** [comment]
I did some looking myself and using the timer on Microsoft Edge I get about 8ms on a old computer.





 
        Christopher
                   
                          


Date: Mon, 15 Feb 2016 20:49:34 -0800

**Comment by Potato42** [comment]
Yeah, get itself seems quite fast and shouldn't be causing the problem.  The fact that it only freezes up when there is a draw loop is pretty weird though.

**Comment by kevinbarabash** [comment]
which version of Chrome is this happening in?  I tried it in 49 and I'm not seeing the issue.

**Comment by lgto4** [comment]
Mine is Version 47.0.2526.106

**Comment by Potato42** [comment]
I have 48.0.2564.109

**Comment by lgto4** [comment]
Version 48.0.2564.116
