### ISSUE TITLE
Scroll issue 

### ISSUE THREAD

**Issue by Cis112233** [Khan/live-editor#555]
https://www.khanacademy.org/computer-programming/testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest/5284522709352448
So I thought I would report this when you have a very long name on the live editor it allows you to scroll right off the webpage the above link is an example. This was discovered on a webpage at first. Should I report this to the zendesk?
https://www.khanacademy.org/computer-programming/booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooom/6248825411207168
I just noticed I have issue 555 :)

**Comment by Gigabyte-Giant** [comment]
If someone is using names like that, they're probably just goofing off.

I suppose program titles could be limited to `x` characters in length, but this really isn't important in my eyes.

**Comment by Cis112233** [comment]
Yeah it is not super important just a odd glitch

**Comment by darrylyeo** [comment]
This would be an easy CSS fix:
`#scratchpad-title {
	word-wrap: break-word;
}`

**Comment by Cis112233** [comment]
Yeah just a quick quality of life improvement

**Comment by pamelafox** [comment]
This fix has to happen outside of live-editor, so yes, please report it in ZenDesk. Thanks!
