### ISSUE TITLE
fill() autocomplete doesn't add a semi-colon anymore

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#566]
There as a recent PR that (I believe) was intended to just change autocomplete behavior for color() and getImage(). However, I think it affected fill(), as it no longer adds a semi-colon. I've found this frustrating over the last few days, as it means I have to get my cursor back outside of the colors in order to add a semi-colon. With fill() and stroke(), I always want the semi-colon.

**Comment by pamelafox** [comment]
@kevinbarabash Can you file this internally? I'd suggest reverting john's recent change as a quick fix. Thanks!

**Comment by kevinbarabash** [comment]
@pamelafox I'll fix this on the weekend.  I stubbed my toe on it too.

**Comment by MikaalSky** [comment]
Please fix asap, it's very annoying when just writing code. :)

**Comment by kevinbarabash** [comment]
I'll do a deploy sometime this week.

**Comment by MatthiasSaihttam** [comment]
This issue really should be closed, as the bug is fixed.

**Comment by kevinbarabash** [comment]
@MatthiasSaihttam thanks.  Someone else must've deployed live-editor to prod.
