### ISSUE TITLE
Yoko Oh noes throws already corrected error

### ISSUE THREAD

**Issue by lavisrap** [Khan/live-editor#568]
I integrated live-editor in my website some time ago. Now I updated to the currents version. Everything works, but Yoko Oh nows appears too often. E.g. after I correct a mistake and change to another line, it shows the old (already corrected) error again. I located the problem in `live-editor.ui.js`  in the `maybeShowErrors` method. There I changed to following code:

```
maybeShowErrors: function maybeShowErrors() {

	if (!this.hasErrors() || !this.editor || !this.editor.getCursor()) {
		return;
	}

	this.setThinkingState();
	// Make doubly sure that we clear the timeout
	window.clearTimeout(this.errorTimeout);
	this.errorTimeout = setTimeout((function () {
		if (this.hasErrors()) {
			this.setErrorState();
		}
	}).bind(this), 60000);
};
```

stripping some functionality- That works fine for me, but I don't know where the stripped functionality would be needed.

**Comment by kevinbarabash** [comment]
The issue goes away when you add `new_error_experience=yes` as a URL param.  We've been using the new error experience for ~6 months and it seems to be going well.  I'd to make it the default and get rid of the old code so that we don't run into situations like this.  

Could you give `new_error_experience=yes` a try and see if it works for you site?  Also, could you post a link to your site.  I'm curious how people are using `live-editor` outside of khanacademy.org.

**Comment by kevinbarabash** [comment]
@lavisrap does adding `?new_error_experience=yes` work for you?

**Comment by lavisrap** [comment]
Hey Kevin,

Am 25.03.2016 um 19:02 schrieb Kevin Barabash:
>
> The issue goes away when you add |new_error_experience=yes| as a URL
> param. We've been using the new error experience for ~6 months and it
> seems to be going well. I'd to make it the default and get rid of the
> old code so that we don't run into situations like this.
>
> Could you give |new_error_experience=yes| a try and see if it works
> for you site?
>
It works! And I like the new experience also. Thanks. (I use it directly
as LiveEditor-Option "newErrorExperience: true")
>
> Also, could you post a link to your site. I'm curious how people are
> using |live-editor| outside of khanacademy.org.
>
Its still very much alpha. But sure you can have a look:
lafisrap.in-berlin.de:8080 (The guy on the home page is a processing
program)


> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/live-editor/issues/568#issuecomment-201393291>
>

-- 
Michael Schmidt
Fingerprint: 
3946 51B0 A7A5 77C3 E656 DECD 1E02 80E6 282C B9E9

Jabber: lavisrap-mint@jabber.ccc.de
Fingerprint:
13645491 563D40C4 81A06B23 DB19285E 1726DAF0

**Comment by kevinbarabash** [comment]
> It works! And I like the new experience also. Thanks. (I use it directly
as LiveEditor-Option "newErrorExperience: true")

Excellent.  I've made the same modification to the demo file.

> But sure you can have a look: lafisrap.in-berlin.de:8080

I tried but the page timed out.
