### ISSUE TITLE
How to use i18n functionality of jshint.js

### ISSUE THREAD

**Issue by lavisrap** [Khan/live-editor#569]
In the live-editor version of jshint.js I found following line:

```
// XXX(jeresig): Used for i18n string extraction
var i18n = { _: function (msg) { return msg; } };

```

For my project I created a js file, that contains an implementation of the i18n._ function, translating strings. That works fine with all parts of the live editor except jshint.js, as it seems to have a distinct variable space (e.g. defines `window` variable at startup).

How can I use these two lines by jeresig from outside jshint.js?

**Comment by kevinbarabash** [comment]
I don't know how `i18n._` gets overwritten for our international sites.  I'll look into it.

**Comment by lavisrap** [comment]
Thx.

**Comment by lavisrap** [comment]
I would be ready to do the programming work, if the i18n integration is not complete. (I need it for a project of mine, which is in German language) I would need some hints from the project how to do it though ...

**Comment by kevinbarabash** [comment]
@lavisrap here are a few steps that we do when translating content:
- extract strings from calls to `i18n._`
- build .pot files from these strings
- upload the .pot files to crowdin
- people on crowdin translate the strings
- download .po with translations from crowdin
- replace the strings in the `i18n._` calls with the translated strings

The main purpose of `i18n._` is to be a placeholder for strings that need to be translated.  It doesn't actually do anything itself other than return the string be it a translated string or otherwise.

We use a python library called babel to help with these steps.

**Comment by lavisrap** [comment]
@ kevinbarabash <https://github.com/kevinbarabash> Thanks, I understand.
It's only that I prefer not to touch the live-editor project for simpler
updates. All other strings I can translate by overloading the
i18n._()-function.

I will upload the pot files of all that I translated ...


Am 10.04.2016 um 03:06 schrieb Kevin Barabash:
>
> @lavisrap <https://github.com/lavisrap> here are a few steps that we
> do when translating content:
>
>   * extract strings from calls to |i18n._|
>   * build .pot files from these strings
>   * upload the .pot files to crowdin
>   * people on crowdin translate the strings
>   * download .po with translations from crowdin
>   * replace the strings in the |i18n._| calls with the translated strings
>
> The main purpose of |i18n._| is to be a placeholder for strings that
> need to be translated. It doesn't actually do anything itself other
> than return the string be it a translated string or otherwise.
>
> We use a python library called babel to help with these steps.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/live-editor/issues/569#issuecomment-207892841>
>

-- 
Michael Schmidt
Fingerprint: 
3946 51B0 A7A5 77C3 E656 DECD 1E02 80E6 282C B9E9

Jabber: lavisrap-mint@jabber.ccc.de
Fingerprint:
13645491 563D40C4 81A06B23 DB19285E 1726DAF0

**Comment by kevinbarabash** [comment]
@lavisrap the translation process results in copies of all of the files in the /build directory that we store elsewhere so modification of the `live-editor` repo isn't necessary.  Also, you don't _have_ to use `crowdin`.  This is simply a service we use to do our translations.  There's lots of tools out there that can be used.
