### ISSUE TITLE
Add support to use TAU 

### ISSUE THREAD

**Issue by Cis112233** [Khan/live-editor#570]
So a lot of people have been wanting to have TAU be a constant like PI or TWO_PI. This is a quick thing and I can do it if I get the location of constants in the code. I will be looking for them right now. The real reason for this issue is so if I find it and add it I can link it to a PR.

**Comment by Gigabyte-Giant** [comment]
I'm pretty sure this isn't a change specific to the live-editor, but ProcessingJS instead...

**Comment by GoToLoop** [comment]
Paste `println(TAU);` @ http://processingjs.org/tools/processing-helper.html and click at the Run button.

**Comment by Cis112233** [comment]
Put that in https://www.khanacademy.org/computer-programming/new/pjs It gives an error. TAU is not defined

**Comment by GoToLoop** [comment]
Whole constant list:
https://github.com/processing-js/processing-js/blob/master/src/Helpers/PConstants.js  

TAU was added on Oct 16, 2013:
https://github.com/processing-js/processing-js/commit/dd70a940d141e4fc2fb969b1812b422827cda168

**Comment by Cis112233** [comment]
Are we a few versions behind?

**Comment by Cis112233** [comment]
https://www.khanacademy.org/computer-programming/tau/3974495678 Tau is not defined

**Comment by kevinbarabash** [comment]
We https://github.com/khan/processing-js which has diverged from https://github.com/processing-js/processing-js.

**Comment by Cis112233** [comment]
Closed: Not an issue that can be fixed in LE

**Comment by Cis112233** [comment]
https://github.com/Khan/processing-js/pull/9 PR created

**Comment by kevinbarabash** [comment]
Cool.  Could you also create a `live-editor` PR that updates the `processing-js` submodule?

**Comment by Cis112233** [comment]
Squashing it on the processing-js khan branch should update it here.

**Comment by Cis112233** [comment]
Total noob question. https://github.com/Khan/live-editor/tree/master/external I see the port of PJS there is there another one?

**Comment by kevinbarabash** [comment]
@Cis112233 to update the submodule you'll want to do the following in the live-editor repo:
- git checkout -b update_pjs_submodule
- cd external/processing-js
- git checkout master
- git pull
- cd ../..
- gulp build
- git commit -a

Then create a pull request for `update_pjs_submodule`.
