### ISSUE TITLE
Access to camera

### ISSUE THREAD

**Issue by SharkFinPro** [Khan/live-editor#578]
Code Is Here
https://www.khanacademy.org/computer-programming/camera/4984174539

**Comment by kevinbarabash** [comment]
The program you linked to contains:
```
var draw = function() {
    background(255);
    for(var each in pixels){
        fill(0);
        text(pixels[each],10,100);
    }
};
```
I don't see how this would give access to the camera.

**Comment by SharkFinProductions** [comment]
oops...i had the wrong link, it is fixed now.
https://www.khanacademy.org/computer-programming/camera/4984174539

**Comment by DozenalFTW** [comment]
I do not like this idea, because people will misuse it.
**-1**

**Comment by kevinbarabash** [comment]
Yes, we need to disallow allow this.

**Comment by DozenalFTW** [comment]
Hack the `window` and `window.constructor.prototype` objects to set the functions to `undefined` or `DUMMY`. This is what you did with `alert` and stuff...

**Comment by SharkFinPro** [comment]
you can still do prompt and alert

**Comment by SharkFinPro** [comment]
^^ 
i have a program that does that
