### ISSUE TITLE
encodeURI() and decodeURI() do not work in Processing.js projects

### ISSUE THREAD

**Issue by EthanMcDonough** [Khan/live-editor#589]
I have tried using `encodeURI()` and `decodeURI()` inside the Processing.js Khan Academy editor and they does not work.  Oh Noes Guy tells me `__env__.encodeURI is not a function`, but I have tried this in Processing.js outside of Khan Academy and it has worked fine.

**Comment by Gigabyte-Giant** [comment]
These functions aren't accessible from within the live-editor environment, because they aren't been made "public" to the scope of a Khan Academy PJS program (these functions are both found under the `window` object, which isn't made available to the user in the live-editor).

**Comment by SharkFinPro** [comment]
You can use window..

**Comment by SpongeJr** [comment]
Generally speaking, the window object is disallowed in the ProecessingJS environment for a variety of reasons.

You can find some more information about this in issues like #547 #309 and related discussion on them, and https://www.khanacademy.org/computing/computer-programming/guidelines/pjs .

The webpage environment provides access to (and permits, guideline-wise) many more features, including the DOM API and window object, and generally, the attitude that that of trying to direct learners towards that if they want to use those features. The ProcessingJS library can be included in projects in that environment, allowing for what I like to call "the best of both worlds".

It may require some additional learning and experimentation to make the move to the webpage environment, but there are tremendous benefits. The curriculum actually takes you about 90% of the way there or more, and a little time on http://processingjs.org/ and some googling can get you the rest of the way.

There are also several templates available for trying to "make the switch" seamlessly. More information on that can be found on a project by @MrMagma that I've sponsored, found here: https://www.khanacademy.org/computer-programming/pjs-embedding/4257230504
as well as in this Help Center article: https://khanacademy.zendesk.com/hc/en-us/articles/203326990

The __env__ error messages might be considered related to #559 .

**Comment by EthanMcDonough** [comment]
Thank you.  I now understand.
