### ISSUE TITLE
Wither my program

### ISSUE THREAD

**Issue by lgto4** [Khan/live-editor#595]
My Projects page shows the thumbnail for https://www.khanacademy.org/discoveries-projects/rotary-switched-spout-circuit/2403508978 but clicking on it takes me to a generic page that says "Oops! Sorry, the page you were trying to load doesn't exist."   

The "discoveries" in the URL seems suspicious.

http://www.khanacademy.org/api/labs/scratchpads/2403508978 does exist.

**Comment by MatthiasSaihttam** [comment]
While this is a severe bug that should be fixed, it has nothing to do with the live editor itself. It looks like, for whatever reason, the api data for the program was messed up and the URL now points at a /discoveries-projects/ directory which doesn't exist. I might be able help you out by using the api to re-save the program, but again, this isn't a live-editor problem. Please file it as an issue at khanacademy.zendesk.com, where generic website bugs belong.

**Comment by lgto4** [comment]
My apologies.
The Zen Desk now has a bug report.

**Comment by kevinbarabash** [comment]
@lgto4 thanks for filing this bug with Zen Desk.
