### ISSUE TITLE
Alternative constructors don't work

### ISSUE THREAD

**Issue by Potato42** [Khan/live-editor#601]
An idiom I sometimes use in JS (that somewhat mimics Python's `classmethods`) is 
```javascript
Constructor.fromSomething = function(something) {
    return new this(...);
};
```

I am pretty sure it used to work on KA, but now I get cryptic errors for simply creating such an alternative constructor.  See [this example program](https://www.khanacademy.org/computer-programming/watfromkhanacademyjs/6294900650672128).

The error seems to be coming from the code rewriting or something as you can't catch it.

**Comment by kevinbarabash** [comment]
I don't think this is a pattern we want to encourage.  The same effect can be accomplished with:
```
Constructor.fromSomething = function(something) {
    return new Constructor(something);
}
```

**Comment by Potato42** [comment]
First off, it doesn't really matter if it is a good pattern, it is a bug that it doesn't work and has a cryptic error message.  I wouldn't be surprised if there are other related bugs.

Also, your way doesn't work with subclasses, while my way works as long as you copy properties attached to the constructor over.

Any ideas where this problem is coming from?

**Comment by kevinbarabash** [comment]
> Also, your way doesn't work with subclasses, while my way works as long as you copy properties attached to the constructor over.

Good point.

> Any ideas where this problem is coming from?

My guess is the `applyInstance` doesn't handle this case correctly.  We transform all `NewExpressions` into calls to `PJSOutput.applyInstance`.  See https://github.com/Khan/live-editor/blob/master/js/output/pjs/pjs-output.js#L559-L588.

**Comment by Potato42** [comment]
I did a little digging, and I think I found [the culprit](https://github.com/Khan/live-editor/blob/0c7ef693aa4ba655e9922269c80a40e0a4c0980e/js/output/pjs/pjs-ast-transforms.js#L297-L303).
That function returns undefined when `node` isn't an `Identifier` or `MemberExpression`.  That undefined gets passed into `Literal`, which becomes a property called `value`, which is why you get an `e.value is undefined`.

**_I started to ramble on after here, so if you want the TL;DR it's "try using `escodegen.generate` instead of `memberExpressionToString`"_**

In our case, we're dealing with a `ThisExpression`, but there are other things you can use too that have the same problem.  For example:

```javascript
var getMyCoolConstructor = function() {
    return function(potato) {
        this.potato = potato;
    };
};

new (getMyCoolConstructor())(42);
```
and
```javascript
// jshint supernew: true
new (function(potato) {
    this.potato = potato;
})(42);
```

And probably a few more things too, although anything that involves a MemberExpression works fine, it just doesn't get a correct `className` when passed into `applyInstance`.

Admittedly, my examples are some pretty contrived and awful code, but they still shouldn't get cryptic errors.  Because this bug doesn't just break `new this()`, we can't just deal with `ThisExpression`s in `memberExpressionToString`, we also need to deal with everything else.  I may be wrong, but I think escodegen (which you are already using) does exactly this, so you could simply replace calls to your `memberExpressionToString` function with calls to `escodegen.generate`.
If there is any reason why you aren't already using escodegen there, you could probably get away with just returning a default value if nothing else is returned, since the strings don't seem to currently be used for anything important based on my quick github code search that didn't seem to reveal any calls (apart from inside tests) to stringify (which seems to be the only thing that uses those strings).

**Comment by kevinbarabash** [comment]
> If there is any reason why you aren't already using escodegen there...

My memory's a bit foggy hear, but I believe that at one point `escodegen.generate` only worked on a `Program` node.  Sounds like that is no longer the case.

I think the strings might be compared somewhere, but it's quite possible that they're not.  I'd have to a thorough audit to make sure.  In the meantime, switching to `escodegen.generate` sounds like an easy quick fix, PRs welcome.

**Comment by Potato42** [comment]
Just checking in, did you see the PR I made?  I thought since I referenced this issue it might notify you, but I guess not.

**Comment by kevinbarabash** [comment]
@Potato42 thanks for pinging me, looking at it.

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/live-editor/pull/602.
