### ISSUE TITLE
Allow more CSS properties

### ISSUE THREAD

**Issue by darrylyeo** [Khan/live-editor#615]
It would be great to have these CSS properties whitelisted (along with any prefixed counterparts). Right now I'm commenting out any CSS declarations that use these properties, then using JS to dynamically remove the comments, which isn't ideal.

``` animation-fill-mode
background-blend-mode
clip-path
font-feature-settings
font-kerning
isolation
mask
mask-clip
mask-image
mask-origin
mask-position
mask-repeat
mix-blend-mode
object-fit
object-position
order
scroll-behavior
shape-image-threshold
shape-margin
shape-outside
text-combine-upright
text-orientation
text-overflow
text-rendering
touch-action
will-change
writing-mode
```

There are a lot more we could add. So far I've just listed properties that have support from at least 2 browsers, prefixes included.

Just to throw it out there: how about ignoring unrecognized property names if inside of a `@supports` query?

**Comment by kevinbarabash** [comment]
It would be nice to have some way to indicate if they are using a browser that doesn't happen to have support for one of these.  I we do add support I'd want auto-prefix them.

**Comment by MikaalSky** [comment]
If anything, the "invalid css property" should be a warning rather than a code breaking issue.

**Comment by pamelafox** [comment]
We now give warnings for unknown CSS properties. There's still an error for invalid CSS property, based on not matching the regex of what a property name can ever look like (letters and dashes).
