### ISSUE TITLE
Width of live editor not changeable

### ISSUE THREAD

**Issue by MatthiasSaihttam** [Khan/live-editor#624]
Since the most recent UI update, the address bar option, `width=` has not worked, with the width staying at 400 no matter what. [Example](https://www.khanacademy.org/cs/i/5510255319515136?width=600&height=600) This is most likely because of #572, but the problem is not as simple as that issue makes it out to be. I put a bit of time into trying to fix this myself, but there are two many factors that need to be inline in order for the width to work properly. The biggest problem is that the Khanacademy.org CSS is also effecting the width of the iframe and the containers for the canvas. I'll try to provide some more detail about exactly what code needs to be changed within the next couple of days (remind me if I forget).

Just to clarify, changing the width using the settings options still works fine, and that's probably why this issue has gone so long unreported.

**Comment by pamelafox** [comment]
This issue is in the internal KA codebase (and I'm working on it there) so I'm going to close it here. Thanks for the nice and simple example.
