### ISSUE TITLE
`with` block slows down code

### ISSUE THREAD

**Issue by ASimnegar** [Khan/live-editor#634]
This issue is quite simple, so I'm not going to elaborate too much.

Processing.js Environment:
```
with (someInstance) { // Oh Noes: Error!
    runSomeCode();
}
```

Khan Academy:
```
with (processingInstance) {
    runOutputCode();
}
```

KA should not use a `with` block to run Processing.js code. `with` is a [deprecated](http://www.2ality.com/2011/06/with-statement.html) feature of JavaScript that [massively slows down](https://jsperf.com/with-statement-vs-lexical-scope) JavaScript code. Using `with` is hypocritical as KA already warns against it in their own live editor. With Processing.js already quite slow and the injection of function call and loop check code into Processing.js programs, any performance gain is good, and removing `with` should make the speed of variable lookup over 7 times faster (using my [JSPerf](https://jsperf.com/with-statement-vs-lexical-scope), tested on Google Chrome).

Thank you for your consideration.

**Comment by kevinbarabash** [comment]
@ASimnegar I removed our use of `with` in https://github.com/Khan/live-editor/commit/55a8053293db945395e687ddab98b8bb71007fa5 quite some time ago.
