### ISSUE TITLE
Ohnoes's error not clear

### ISSUE THREAD

**Issue by cursorweb** [Khan/live-editor#648]
Ohnoes says "Something is wrong with your website".
This is not clear at all. He doesn't tell you the exact location where it is wrong

**Comment by CosignCosine** [comment]
Hello, cursorweb!
The webpage console should have more detailed information about the error that your code produced. 
Use this list to find the keybinding to open the console on your browser: https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers
