### ISSUE TITLE
"animation-fill-mode does not exist" error?

### ISSUE THREAD

**Issue by JettBurns14** [Khan/live-editor#650]
I'm getting this error when trying to use `animation-fill-mode`, line 56 [here](https://www.khanacademy.org/computer-programming/27-other-css-animation-properties/6556208392601600).
![image](https://user-images.githubusercontent.com/24257648/38118812-ec4a52ea-3382-11e8-888e-842bad27e231.png)
This is my first time using this property, and I'm disappointed it won't work.

**Comment by darrylyeo** [comment]
Looks like another property to add to the list on #615.

**Comment by pamelafox** [comment]
It's a warning now, so you can experiment with the new CSS props on KA. (And share what you learn, of course :)
