### ISSUE TITLE
If Else and other statements

### ISSUE THREAD

**Issue by mbartlett21** [Khan/live-editor#664]
Why does Oh Noes need a block statement after if, else, etc.
I find it a bit annoying because most of my if statements only have a single statement after them :(

**Comment by Dalendrion** [comment]
It's good practice to always have curly braces.
Say an inexperienced programmer wants to add a second line to that if
statement. The programmer might forget to add the curly braces, thus
introducing a bug.
As it happens, most KA users are indeed inexperienced.

**Comment by naclcaleb** [comment]
This is still open, but could be closed...
