### ISSUE TITLE
Multi-line strings

### ISSUE THREAD

**Issue by morganb21** [Khan/live-editor#689]
I cannot create multiline strings using the backtick key like this:
```javascript
var a = `This is a
multiline string`;
```

**Comment by pamelafox** [comment]
Template strings (with backticks) are an ES6 feature. LiveEditor does not currently support ES6 feature. 

Template strings in particular were filed as a request here:
https://github.com/Khan/live-editor/issues/629
So I'll close this issue as a duplicate.

We have no immediate plans to support ES6, so you may want to try other editors if that is a need for you.

**Comment by mbartlett21** [comment]
What about the code below?
It doesn't like it, though it works with `// jshint multistr:true`
```javascript
var str = "This is a very long string\
 that goes over multiple lines";
```
