### ISSUE TITLE
Infinite Loop Protect not catching for loop, crashing browser.

### ISSUE THREAD

**Issue by ccaven** [Khan/live-editor#698]
**Issue**
When scripting a `for` loop, some people start out like this:
```
for () {
   
}
```
then go on to type the statements inside the `for ()` like this:
```
for (var i = 0;) {

}
```
then
```
for (var i = 0; i < 10;) {
   
}
```
and as soon as they type the second semicolon, the `for` loop is technically valid but it's an infinite loop because `i` is not increasing with each iter. The infinite loop protection is not catching it.

When I do it, my browser freezes and if I'm using Firefox, I get this message:
_"Something is slowing down your webpage. Stop | Wait"_
clicking `wait` doesn't do anything, and `stop` closes the tab.

Hope helps.

**Comment by pamelafox** [comment]
Thank you for the replication steps! It appears the LoopProtector isn't working for this case, we'll need to investigate why.

**Comment by kevinbarabash** [comment]
It's probably an issue with the AST transform.  It's probably not handling the empty body case properly.

**Comment by pamelafox** [comment]
I believe this is due to a bug I caused in late August. I just sent this PR for it:
https://github.com/Khan/live-editor/pull/701/files

**Comment by pamelafox** [comment]
The fix was deployed, so I'm closing this issue. Please re-open if you believe it is still happening.
