### ISSUE TITLE
PVector add method is incorrectly documented or implemented

### ISSUE THREAD

**Issue by lgto4** [Khan/live-editor#711]
```
var v = new PVector();
println(v);
v.add(1, 2);
println(v);
```
The Processing.js PVector add method expects one or three arguments.  Khan Academy users following Khan Academy documentation are disappointed.

**Comment by pamelafox** [comment]
Good catch, added "z" to the documentation: https://www.khanacademy.org/computer-programming/pvectoraddx-y/4680458877009920 How's that look?

**Comment by lgto4** [comment]
The updated documentation looks good to me.

**Comment by pamelafox** [comment]
Great, closing!
